-- October 2026 Mess Menu — MH from file 1, LH from file 2
DELETE FROM menus WHERE date >= '2026-10-01' AND date <= '2026-10-31';

INSERT INTO menus (block_category, date, meal_type, items, is_special) VALUES
  ('MH', '2026-10-01', 'breakfast', 'Methi Poori (3 Pcs standard size), Lemon Sevai, Aloo Mutter Curry (1), Chickpea Masala (15, 29), Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Onion Omlet (Non-Veg)', false),
  ('MH', '2026-10-01', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Sorrel Leaves Dal (Gongura Pappu), Sambar, Pudina Rice, Guthi Vankaya Curry, Ridge Gourd Fry, Finger Fryums, Lemon Water w/o Sugar + Sabja Seeds, Potlakaya Perugu Chutney, Ghee + Podi', false),
  ('MH', '2026-10-01', 'snacks', 'Veg Puff (1, 29), Boiled Peanuts with Onion/Tomato (15), Tomato Sauce, Tea/Coffee/Milk', false),
  ('MH', '2026-10-01', 'dinner', 'Onions & Lemon Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchuria, Noodles, Tomato Sauce, Butternut Squash Curry, Thick Curd, Banana, Ginger Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-15', 'breakfast', 'Methi Poori (3 Pcs standard size), Lemon Sevai, Aloo Mutter Curry (1), Chickpea Masala (15, 29), Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Onion Omlet (Non-Veg)', false),
  ('MH', '2026-10-15', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Sorrel Leaves Dal (Gongura Pappu), Sambar, Pudina Rice, Guthi Vankaya Curry, Ridge Gourd Fry, Finger Fryums, Lemon Water w/o Sugar + Sabja Seeds, Potlakaya Perugu Chutney, Ghee + Podi', false),
  ('MH', '2026-10-15', 'snacks', 'Veg Puff (1, 29), Boiled Peanuts with Onion/Tomato (15), Tomato Sauce, Tea/Coffee/Milk', false),
  ('MH', '2026-10-15', 'dinner', 'Onions & Lemon Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchuria, Noodles, Tomato Sauce, Butternut Squash Curry, Thick Curd, Banana, Ginger Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-29', 'breakfast', 'Methi Poori (3 Pcs standard size), Lemon Sevai, Aloo Mutter Curry (1), Chickpea Masala (15, 29), Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Onion Omlet (Non-Veg)', false),
  ('MH', '2026-10-29', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Sorrel Leaves Dal (Gongura Pappu), Sambar, Pudina Rice, Guthi Vankaya Curry, Ridge Gourd Fry, Finger Fryums, Lemon Water w/o Sugar + Sabja Seeds, Potlakaya Perugu Chutney, Ghee + Podi', false),
  ('MH', '2026-10-29', 'snacks', 'Veg Puff (1, 29), Boiled Peanuts with Onion/Tomato (15), Tomato Sauce, Tea/Coffee/Milk', false),
  ('MH', '2026-10-29', 'dinner', 'Onions & Lemon Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchuria, Noodles, Tomato Sauce, Butternut Squash Curry, Thick Curd, Banana, Ginger Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-02', 'breakfast', 'Uggani + Mirchi Bajji, Vegetable Daliya Kitchidi, Coconut Chutney, Mango Pickle, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-02', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Red Lentil Pumpkin Curry, Papad, Butter Milk, Beerakaya Chutney, Moong Dal Payasam', false),
  ('MH', '2026-10-02', 'snacks', 'Raw Banana Bhajji 2 PCs (Less Oily), Coconut Coriander Chutney, Ginger Tea/Coffee/Milk', false),
  ('MH', '2026-10-02', 'dinner', 'Onions & Lemon Salad, Lacha Paratha, White Rice, Pesara Pappu, Sambar, Garlic Chicken Curry (Non-Veg), Paneer Lababdar (Veg), Tomato Peas Capsicum Masala, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Mango Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-16', 'breakfast', 'Uggani + Mirchi Bajji, Vegetable Daliya Kitchidi, Coconut Chutney, Mango Pickle, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-16', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Red Lentil Pumpkin Curry, Papad, Butter Milk, Beerakaya Chutney, Moong Dal Payasam', false),
  ('MH', '2026-10-16', 'snacks', 'Raw Banana Bhajji 2 PCs (Less Oily), Coconut Coriander Chutney, Ginger Tea/Coffee/Milk', false),
  ('MH', '2026-10-16', 'dinner', 'Onions & Lemon Salad, Lacha Paratha, White Rice, Pesara Pappu, Sambar, Garlic Chicken Curry (Non-Veg), Paneer Lababdar (Veg), Tomato Peas Capsicum Masala, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Mango Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-30', 'breakfast', 'Uggani + Mirchi Bajji, Vegetable Daliya Kitchidi, Coconut Chutney, Mango Pickle, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-30', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Red Lentil Pumpkin Curry, Papad, Butter Milk, Beerakaya Chutney, Moong Dal Payasam', false),
  ('MH', '2026-10-30', 'snacks', 'Raw Banana Bhajji 2 PCs (Less Oily), Coconut Coriander Chutney, Ginger Tea/Coffee/Milk', false),
  ('MH', '2026-10-30', 'dinner', 'Onions & Lemon Salad, Lacha Paratha, White Rice, Pesara Pappu, Sambar, Garlic Chicken Curry (Non-Veg), Paneer Lababdar (Veg), Tomato Peas Capsicum Masala, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Mango Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-03', 'breakfast', 'Mix Veg Utappam - 2 Pcs Std Size, Vegetable Poha, Peanut Chutney, Tomato Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-03', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Dondakaya Stir Fry, Chole Curry, Papad, Majiga Pulusu, Avakaya (Mango Pickle), Ghee + Podi', false),
  ('MH', '2026-10-03', 'snacks', 'Punugulu 8 Pcs Medium Size, Groundnut/Coconut Chutney, Cold Badam Milk (1 Medium Glass)', false),
  ('MH', '2026-10-03', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Bendakaya (Bhindi) Pulusu, Vegetable Fried Rice, Gobhi Manchuria, Tomato Sauce, Cabbage Beans Poriyal, Thick Curd, Fruit Custard with Pine Apple (3), and Custard Apple (17, 31), Red Chilli Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-17', 'breakfast', 'Mix Veg Utappam - 2 Pcs Std Size, Vegetable Poha, Peanut Chutney, Tomato Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-17', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Dondakaya Stir Fry, Chole Curry, Papad, Majiga Pulusu, Avakaya (Mango Pickle), Ghee + Podi', false),
  ('MH', '2026-10-17', 'snacks', 'Punugulu 8 Pcs Medium Size, Groundnut/Coconut Chutney, Cold Badam Milk (1 Medium Glass)', false),
  ('MH', '2026-10-17', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Bendakaya (Bhindi) Pulusu, Vegetable Fried Rice, Gobhi Manchuria, Tomato Sauce, Cabbage Beans Poriyal, Thick Curd, Fruit Custard with Pine Apple (3), and Custard Apple (17, 31), Red Chilli Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-31', 'breakfast', 'Mix Veg Utappam - 2 Pcs Std Size, Vegetable Poha, Peanut Chutney, Tomato Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-31', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Dondakaya Stir Fry, Chole Curry, Papad, Majiga Pulusu, Avakaya (Mango Pickle), Ghee + Podi', false),
  ('MH', '2026-10-31', 'snacks', 'Punugulu 8 Pcs Medium Size, Groundnut/Coconut Chutney, Cold Badam Milk (1 Medium Glass)', false),
  ('MH', '2026-10-31', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Bendakaya (Bhindi) Pulusu, Vegetable Fried Rice, Gobhi Manchuria, Tomato Sauce, Cabbage Beans Poriyal, Thick Curd, Fruit Custard with Pine Apple (3), and Custard Apple (17, 31), Red Chilli Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-04', 'breakfast', 'Shavige Bath, Paneer Paratha - 2 Pcs Thin, Coconut Chutney, Thick Curd, Mango Pickle, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Bhurji (Non-Veg)', false),
  ('MH', '2026-10-04', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Fry, Chicken Dum Biryani/Paneer Dum Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Triangular Fryums, Nannari Sharbath, Fresh Gongura Chutney, Basundhi (60 ml)', false),
  ('MH', '2026-10-04', 'snacks', 'Plum Cake (Egg Less) 1 Big Pc, Masala Tea/Coffee/Milk', false),
  ('MH', '2026-10-04', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Ragi Idly, Groundnut Chutney, Dondakaya Fry, Vegetable Kurma Gravy, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-18', 'breakfast', 'Shavige Bath, Paneer Paratha - 2 Pcs Thin, Coconut Chutney, Thick Curd, Mango Pickle, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Bhurji (Non-Veg)', false),
  ('MH', '2026-10-18', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Fry, Chicken Dum Biryani/Paneer Dum Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Triangular Fryums, Nannari Sharbath, Fresh Gongura Chutney, Basundhi (60 ml)', false),
  ('MH', '2026-10-18', 'snacks', 'Plum Cake (Egg Less) 1 Big Pc, Masala Tea/Coffee/Milk', false),
  ('MH', '2026-10-18', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Ragi Idly, Groundnut Chutney, Dondakaya Fry, Vegetable Kurma Gravy, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-05', 'breakfast', 'Ghee + Veg Pongal, Bhature - 2 Pcs Big, Groundnut Chutney, Sambar, Chole Curry, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-05', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Tomato Rice, Pesara Punugulu Curry (Pakka Andhra Style), Capsicum Tomato Masala, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Jilebi, Ghee + Podi', false),
  ('MH', '2026-10-05', 'snacks', 'Dry Maggi (Non-Sticky), Tomato Sauce, Tea/Coffee/Milk', false),
  ('MH', '2026-10-05', 'dinner', 'Onions & Lemon Salad, Methi Roti, White Rice, Pesara Pappu, Tomato Rasam, Bhagara Rice, Chicken Mughlai (Non-Veg), Paneer Butter Masala (Veg), Ladies Finger Boiled Fry, Thick Curd, Mixed Fruit Salad (Black Grapes, Banana, Pomegranate), Gongura Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-19', 'breakfast', 'Ghee + Veg Pongal, Bhature - 2 Pcs Big, Groundnut Chutney, Sambar, Chole Curry, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-19', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Tomato Rice, Pesara Punugulu Curry (Pakka Andhra Style), Capsicum Tomato Masala, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Jilebi, Ghee + Podi', false),
  ('MH', '2026-10-19', 'snacks', 'Dry Maggi (Non-Sticky), Tomato Sauce, Tea/Coffee/Milk', false),
  ('MH', '2026-10-19', 'dinner', 'Onions & Lemon Salad, Methi Roti, White Rice, Pesara Pappu, Tomato Rasam, Bhagara Rice, Chicken Mughlai (Non-Veg), Paneer Butter Masala (Veg), Ladies Finger Boiled Fry, Thick Curd, Mixed Fruit Salad (Black Grapes, Banana, Pomegranate), Gongura Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-06', 'breakfast', 'Onion Dosa (6), Masala Dosa (20) - 2 Pcs Std Size, Vada Pav, Coconut Chutney, Mint Chutney, Brown Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-06', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Dosakaya Pappu, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Ghee + Podi', false),
  ('MH', '2026-10-06', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Ginger Tea/Coffee/Milk', false),
  ('MH', '2026-10-06', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Guava Fruit, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-20', 'breakfast', 'Onion Dosa (6), Masala Dosa (20) - 2 Pcs Std Size, Vada Pav, Coconut Chutney, Mint Chutney, Brown Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-20', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Dosakaya Pappu, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Ghee + Podi', false),
  ('MH', '2026-10-20', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Ginger Tea/Coffee/Milk', false),
  ('MH', '2026-10-20', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Guava Fruit, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-07', 'breakfast', 'Methi Vada (Big size 3pcs, if not 4pcs), Cucumber Poha, Sambar, Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Onion Omlet  (Non-Veg)', false),
  ('MH', '2026-10-07', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Amaranthus Dal, Pachi Pulusu, Bhagara Rice, Hyderabadi Chicken Curry, Shahi Paneer, Vegetable Jalfrezi, Butter Milk, Fresh Vegetable Chutney, Badusha', false),
  ('MH', '2026-10-07', 'snacks', 'Onion Soft Pakoda (Less Oily), Tomato Chutney, Tea/Coffee/Milk', false),
  ('MH', '2026-10-07', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Broken Wheat Rava Upma, Coconut Chutney, Bottle Guard Chana Dal Fry, Aloo Mutter Curry, Thick Curd, Mixed Fruit Salad (Pomegranate, Pine Apple, Green grapes), Lemon Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-21', 'breakfast', 'Methi Vada (Big size 3pcs, if not 4pcs), Cucumber Poha, Sambar, Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Onion Omlet  (Non-Veg)', false),
  ('MH', '2026-10-21', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Amaranthus Dal, Pachi Pulusu, Bhagara Rice, Hyderabadi Chicken Curry, Shahi Paneer, Vegetable Jalfrezi, Butter Milk, Fresh Vegetable Chutney, Badusha', false),
  ('MH', '2026-10-21', 'snacks', 'Onion Soft Pakoda (Less Oily), Tomato Chutney, Tea/Coffee/Milk', false),
  ('MH', '2026-10-21', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Broken Wheat Rava Upma, Coconut Chutney, Bottle Guard Chana Dal Fry, Aloo Mutter Curry, Thick Curd, Mixed Fruit Salad (Pomegranate, Pine Apple, Green grapes), Lemon Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-08', 'breakfast', 'Poori (3 pcs standard size), Rice Rava Kitchidi, Aloo Basin Chutney, Dal Chutney, Brown Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Egg Bhurji (Non-Veg)', false),
  ('MH', '2026-10-08', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Ridge Gourd Dal, Sambar, Pudina Rice, Guthi Vankaya Curry, Kala Chana Masala, Finger Fryums, Lemon Water + Sabja Seeds, Potlakaya Perugu Chutney, Ghee + Podi', false),
  ('MH', '2026-10-08', 'snacks', 'Sambar Vada 2 Pcs (Separate), Masala Tea/Coffee/Milk', false),
  ('MH', '2026-10-08', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchurian, Noodles, Tomato Sauce, Rajma Masala, Thick Curd, Sweet Lime, Ginger Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-22', 'breakfast', 'Poori (3 pcs standard size), Rice Rava Kitchidi, Aloo Basin Chutney, Dal Chutney, Brown Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Egg Bhurji (Non-Veg)', false),
  ('MH', '2026-10-22', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Ridge Gourd Dal, Sambar, Pudina Rice, Guthi Vankaya Curry, Kala Chana Masala, Finger Fryums, Lemon Water + Sabja Seeds, Potlakaya Perugu Chutney, Ghee + Podi', false),
  ('MH', '2026-10-22', 'snacks', 'Sambar Vada 2 Pcs (Separate), Masala Tea/Coffee/Milk', false),
  ('MH', '2026-10-22', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchurian, Noodles, Tomato Sauce, Rajma Masala, Thick Curd, Sweet Lime, Ginger Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-09', 'breakfast', 'Pesarattu Thin 2 Pcs Std Size, Tomato Suji Upma, Coconut Chutney, Ginger Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-09', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Cauli Flower Stir Fry (Less Oil), Papad, Lassi, Beerakaya Chutney, Carrot Halwa', false),
  ('MH', '2026-10-09', 'snacks', 'Mysore Bonda 2 Pcs Std Size (Less Oily), Coconut Chutney, Tea/Coffee/Milk', false),
  ('MH', '2026-10-09', 'dinner', 'Onions & Lemon Salad, Beetroot Chapathi (9, 23), White Rice, Dal, Sambar, Kadai Chicken (Non-Veg), Kadai Paneer (Veg), Amritsari Chole, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Fresh Vegetable Chutney/Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-23', 'breakfast', 'Pesarattu Thin 2 Pcs Std Size, Tomato Suji Upma, Coconut Chutney, Ginger Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-23', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Cauli Flower Stir Fry (Less Oil), Papad, Lassi, Beerakaya Chutney, Carrot Halwa', false),
  ('MH', '2026-10-23', 'snacks', 'Mysore Bonda 2 Pcs Std Size (Less Oily), Coconut Chutney, Tea/Coffee/Milk', false),
  ('MH', '2026-10-23', 'dinner', 'Onions & Lemon Salad, Beetroot Chapathi (9, 23), White Rice, Dal, Sambar, Kadai Chicken (Non-Veg), Kadai Paneer (Veg), Amritsari Chole, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Fresh Vegetable Chutney/Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-10', 'breakfast', 'Uggani + Mirchi Bajji, Moong Dal Palak Tepla (Hand Made) 2 Pcs, Groundnut Chutney, Onion Tomato Chutney, Brown Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-10', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Cauli Flower Fry, Chole Curry, Papad, Majjiga Pulusu, Avakaya (Mango Pickle), Ghee + Podi', false),
  ('MH', '2026-10-10', 'snacks', 'Vada Pav 2 Pcs, Mint Sauce, Cold Badam Milk (1 Medium Glass)', false),
  ('MH', '2026-10-10', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Drumstick Sambar, Ghee + Podi + Idly, Coconut Chutney, Tomato Baingan Fry, Thick Curd, Muskmelon Cut Fruit, Red Chilli Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-24', 'breakfast', 'Uggani + Mirchi Bajji, Moong Dal Palak Tepla (Hand Made) 2 Pcs, Groundnut Chutney, Onion Tomato Chutney, Brown Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-24', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Cauli Flower Fry, Chole Curry, Papad, Majjiga Pulusu, Avakaya (Mango Pickle), Ghee + Podi', false),
  ('MH', '2026-10-24', 'snacks', 'Vada Pav 2 Pcs, Mint Sauce, Cold Badam Milk (1 Medium Glass)', false),
  ('MH', '2026-10-24', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Drumstick Sambar, Ghee + Podi + Idly, Coconut Chutney, Tomato Baingan Fry, Thick Curd, Muskmelon Cut Fruit, Red Chilli Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-11', 'breakfast', 'Shavige Bath, Mix Veg Paratha (2 Pcs Thin), Groundnut Chutney, Thick Curd, Mango Pickle, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Bhurji (Non-Veg)', false),
  ('MH', '2026-10-11', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Makhani, Chicken Fry Piece Biryani/Paneer Fry Piece Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Fryums, Nannari Sharbath, Fresh Gongura Chutney, Vanilla Ice Cream  (Not Frozen Dessert)', false),
  ('MH', '2026-10-11', 'snacks', 'Dahi Papdi Chat, Onions, Tea/Coffee/Milk', false),
  ('MH', '2026-10-11', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Karam Dosa (2 Pcs Thin), Coconut Chutney, Dondakaya Fry, Vegetable Kolhapuri, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-25', 'breakfast', 'Shavige Bath, Mix Veg Paratha (2 Pcs Thin), Groundnut Chutney, Thick Curd, Mango Pickle, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Bhurji (Non-Veg)', false),
  ('MH', '2026-10-25', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Makhani, Chicken Fry Piece Biryani/Paneer Fry Piece Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Fryums, Nannari Sharbath, Fresh Gongura Chutney, Vanilla Ice Cream  (Not Frozen Dessert)', false),
  ('MH', '2026-10-25', 'snacks', 'Dahi Papdi Chat, Onions, Tea/Coffee/Milk', false),
  ('MH', '2026-10-25', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Karam Dosa (2 Pcs Thin), Coconut Chutney, Dondakaya Fry, Vegetable Kolhapuri, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-12', 'breakfast', 'Roasted Idli Upma, Bhature - 3 Pcs Big, Coconut Chutney, Chole Curry, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Omlet (Non-Veg)', false),
  ('MH', '2026-10-12', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Ghee Rice, Crispy Dragon Potato, Drumstick Tomato Curry, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Mysore Pak, Ghee + Podi', false),
  ('MH', '2026-10-12', 'snacks', 'Chatakedar Corn, Lemon Sauce, Masala Tea/Coffee/Milk', false),
  ('MH', '2026-10-12', 'dinner', 'Onions & Lemon Salad, Methi Roti, White Rice, Dal Tadka, Tomato Rasam, Bhagara Rice, Chettinad Chicken Curry (Non-Veg), Paneer Green Peas Masala (Veg), Bhindi Masala, Thick Curd, Mixed Fruit Salad (Black Grapes, Banana, Pomegranate), Gongura Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-26', 'breakfast', 'Roasted Idli Upma, Bhature - 3 Pcs Big, Coconut Chutney, Chole Curry, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Omlet (Non-Veg)', false),
  ('MH', '2026-10-26', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Ghee Rice, Crispy Dragon Potato, Drumstick Tomato Curry, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Mysore Pak, Ghee + Podi', false),
  ('MH', '2026-10-26', 'snacks', 'Chatakedar Corn, Lemon Sauce, Masala Tea/Coffee/Milk', false),
  ('MH', '2026-10-26', 'dinner', 'Onions & Lemon Salad, Methi Roti, White Rice, Dal Tadka, Tomato Rasam, Bhagara Rice, Chettinad Chicken Curry (Non-Veg), Paneer Green Peas Masala (Veg), Bhindi Masala, Thick Curd, Mixed Fruit Salad (Black Grapes, Banana, Pomegranate), Gongura Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-13', 'breakfast', 'Ghee Podi Dosa (2 Pcs Thin), Pav Bhaji, Coconut Chutney, Sambar, Mint Chutney, White Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Scrambled Egg (Non-Veg)', false),
  ('MH', '2026-10-13', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Amaranthus Dal, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Ghee + Podi', false),
  ('MH', '2026-10-13', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Tea/Coffee/Milk', false),
  ('MH', '2026-10-13', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Sweet Lime, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-27', 'breakfast', 'Ghee Podi Dosa (2 Pcs Thin), Pav Bhaji, Coconut Chutney, Sambar, Mint Chutney, White Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Scrambled Egg (Non-Veg)', false),
  ('MH', '2026-10-27', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Amaranthus Dal, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Ghee + Podi', false),
  ('MH', '2026-10-27', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Tea/Coffee/Milk', false),
  ('MH', '2026-10-27', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Sweet Lime, Tomato Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-14', 'breakfast', 'Methu Vada (Big size 3pcs, if not 4pcs), Vegetable Poha, Sambar, Coconut Chutney, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-14', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Gongura (Sorrel Leaves) Dal, Sambar, Vegetable Dum Pulav, Andhra Chicken Fry, Kaju Tomato Paneer Fry, Red Beans Curry, Butter Milk, Coriander + Tomato Chutney, Gulab Jamun', false),
  ('MH', '2026-10-14', 'snacks', 'Bandi Style Ragda Chat, Onion Small pieces, Ginger Tea/Coffee/Milk', false),
  ('MH', '2026-10-14', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Sooji Upma, Coconut Chutney, Bottle Guard Tomato Stir Fry, Soya Chunks Masala, Thick Curd, Green Grapes, Lemon Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-28', 'breakfast', 'Methu Vada (Big size 3pcs, if not 4pcs), Vegetable Poha, Sambar, Coconut Chutney, Brown Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg (Non-Veg)', false),
  ('MH', '2026-10-28', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Gongura (Sorrel Leaves) Dal, Sambar, Vegetable Dum Pulav, Andhra Chicken Fry, Kaju Tomato Paneer Fry, Red Beans Curry, Butter Milk, Coriander + Tomato Chutney, Gulab Jamun', false),
  ('MH', '2026-10-28', 'snacks', 'Bandi Style Ragda Chat, Onion Small pieces, Ginger Tea/Coffee/Milk', false),
  ('MH', '2026-10-28', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Sooji Upma, Coconut Chutney, Bottle Guard Tomato Stir Fry, Soya Chunks Masala, Thick Curd, Green Grapes, Lemon Pickle, Milk + Cofee Powder', false),
  ('MH', '2026-10-01', 'breakfast', 'Methi Poori (3 Pcs standard size), Lemon Sevai, Aloo Mutter Curry (1), Chickpea Masala (15, 29), Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Grapes Fresh Juice with Light Sugar, Cornflakes, Masala Onion Omlet (Non-Veg), Boiled Chickpeas Salad (Veg)', true),
  ('MH', '2026-10-01', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Sorrel Leaves Dal (Gongura Pappu), Sambar, Pudina Rice, Guthi Vankaya Curry, Ridge Gourd Fry, Finger Fryums, Lemon Water w/o Sugar + Sabja Seeds, Potlakaya Perugu Chutney, Shahi Ki Tukda, Ghee + Podi', true),
  ('MH', '2026-10-01', 'snacks', 'Veg Puff (1, 29), Boiled Peanuts with Onion/Tomato (15), Tomato Sauce, Tea/Coffee/Milk', true),
  ('MH', '2026-10-01', 'dinner', 'Onions & Lemon Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchuria, Noodles, Tomato Sauce, Chicken 65/Andhra Fish Fry (NV), Paneer 65/ Baby Corn 65 (Veg), Butternut Squash Curry, Thick Curd, Banana, Ginger Pickle, Milk + Cofee Powder, Creamy Mushroom Soup', true),
  ('MH', '2026-10-15', 'breakfast', 'Methi Poori (3 Pcs standard size), Lemon Sevai, Aloo Mutter Curry (1), Chickpea Masala (15, 29), Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Grapes Fresh Juice with Light Sugar, Cornflakes, Masala Onion Omlet (Non-Veg), Boiled Chickpeas Salad (Veg)', true),
  ('MH', '2026-10-15', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Sorrel Leaves Dal (Gongura Pappu), Sambar, Pudina Rice, Guthi Vankaya Curry, Ridge Gourd Fry, Finger Fryums, Lemon Water w/o Sugar + Sabja Seeds, Potlakaya Perugu Chutney, Shahi Ki Tukda, Ghee + Podi', true),
  ('MH', '2026-10-15', 'snacks', 'Veg Puff (1, 29), Boiled Peanuts with Onion/Tomato (15), Tomato Sauce, Tea/Coffee/Milk', true),
  ('MH', '2026-10-15', 'dinner', 'Onions & Lemon Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchuria, Noodles, Tomato Sauce, Chicken 65/Andhra Fish Fry (NV), Paneer 65/ Baby Corn 65 (Veg), Butternut Squash Curry, Thick Curd, Banana, Ginger Pickle, Milk + Cofee Powder, Creamy Mushroom Soup', true),
  ('MH', '2026-10-29', 'breakfast', 'Methi Poori (3 Pcs standard size), Lemon Sevai, Aloo Mutter Curry (1), Chickpea Masala (15, 29), Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Grapes Fresh Juice with Light Sugar, Cornflakes, Masala Onion Omlet (Non-Veg), Boiled Chickpeas Salad (Veg)', true),
  ('MH', '2026-10-29', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Sorrel Leaves Dal (Gongura Pappu), Sambar, Pudina Rice, Guthi Vankaya Curry, Ridge Gourd Fry, Finger Fryums, Lemon Water w/o Sugar + Sabja Seeds, Potlakaya Perugu Chutney, Shahi Ki Tukda, Ghee + Podi', true),
  ('MH', '2026-10-29', 'snacks', 'Veg Puff (1, 29), Boiled Peanuts with Onion/Tomato (15), Tomato Sauce, Tea/Coffee/Milk', true),
  ('MH', '2026-10-29', 'dinner', 'Onions & Lemon Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchuria, Noodles, Tomato Sauce, Chicken 65/Andhra Fish Fry (NV), Paneer 65/ Baby Corn 65 (Veg), Butternut Squash Curry, Thick Curd, Banana, Ginger Pickle, Milk + Cofee Powder, Creamy Mushroom Soup', true),
  ('MH', '2026-10-02', 'breakfast', 'Uggani + Mirchi Bajji, Vegetable Daliya Kitchidi, Coconut Chutney, Mango Pickle, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Pineapple Fresh Juice with Light Sugar, Museli, Boiled Egg (Non-Veg), Boiled Peanut Sundal (Veg)', true),
  ('MH', '2026-10-02', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Red Lentil Pumpkin Curry, Papad, Butter Milk, Beerakaya Chutney, Moong Dal Payasam', true),
  ('MH', '2026-10-02', 'snacks', 'Raw Banana Bhajji 2 PCs (Less Oily), Coconut Coriander Chutney, Ginger Tea/Coffee/Milk', true),
  ('MH', '2026-10-02', 'dinner', 'Onions & Lemon Salad, Lacha Paratha, White Rice, Pesara Pappu, Sambar, Garlic Chicken Curry (Non-Veg), Paneer Lababdar (Veg), Tomato Peas Capsicum Masala, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Mango Pickle, Milk + Cofee Powder, Mix Veg Raagi Soup', true),
  ('MH', '2026-10-16', 'breakfast', 'Uggani + Mirchi Bajji, Vegetable Daliya Kitchidi, Coconut Chutney, Mango Pickle, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Pineapple Fresh Juice with Light Sugar, Museli, Boiled Egg (Non-Veg), Boiled Peanut Sundal (Veg)', true),
  ('MH', '2026-10-16', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Red Lentil Pumpkin Curry, Papad, Butter Milk, Beerakaya Chutney, Moong Dal Payasam', true),
  ('MH', '2026-10-16', 'snacks', 'Raw Banana Bhajji 2 PCs (Less Oily), Coconut Coriander Chutney, Ginger Tea/Coffee/Milk', true),
  ('MH', '2026-10-16', 'dinner', 'Onions & Lemon Salad, Lacha Paratha, White Rice, Pesara Pappu, Sambar, Garlic Chicken Curry (Non-Veg), Paneer Lababdar (Veg), Tomato Peas Capsicum Masala, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Mango Pickle, Milk + Cofee Powder, Mix Veg Raagi Soup', true),
  ('MH', '2026-10-30', 'breakfast', 'Uggani + Mirchi Bajji, Vegetable Daliya Kitchidi, Coconut Chutney, Mango Pickle, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Pineapple Fresh Juice with Light Sugar, Museli, Boiled Egg (Non-Veg), Boiled Peanut Sundal (Veg)', true),
  ('MH', '2026-10-30', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Red Lentil Pumpkin Curry, Papad, Butter Milk, Beerakaya Chutney, Moong Dal Payasam', true),
  ('MH', '2026-10-30', 'snacks', 'Raw Banana Bhajji 2 PCs (Less Oily), Coconut Coriander Chutney, Ginger Tea/Coffee/Milk', true),
  ('MH', '2026-10-30', 'dinner', 'Onions & Lemon Salad, Lacha Paratha, White Rice, Pesara Pappu, Sambar, Garlic Chicken Curry (Non-Veg), Paneer Lababdar (Veg), Tomato Peas Capsicum Masala, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Mango Pickle, Milk + Cofee Powder, Mix Veg Raagi Soup', true),
  ('MH', '2026-10-03', 'breakfast', 'Mix Veg Utappam - 2 Pcs Std Size, Vegetable Poha, Peanut Chutney, Tomato Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Guava Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Sweet Potato Salad (Veg)', true),
  ('MH', '2026-10-03', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Dondakaya Stir Fry, Chole Curry, Papad, Majiga Pulusu, Avakaya (Mango Pickle), Carrot Halwa, Ghee + Podi', true),
  ('MH', '2026-10-03', 'snacks', 'Punugulu 8 Pcs Medium Size, Groundnut/Coconut Chutney, Cold Badam Milk (1 Medium Glass)', true),
  ('MH', '2026-10-03', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Bendakaya (Bhindi) Pulusu, Vegetable Fried Rice, Gobhi Manchuria, Tomato Sauce, Cabbage Beans Poriyal, Thick Curd, Fruit Custard with Pine Apple (3), and Custard Apple (17, 31), Red Chilli Pickle, Milk + Cofee Powder, Red Lentil Soup', true),
  ('MH', '2026-10-17', 'breakfast', 'Mix Veg Utappam - 2 Pcs Std Size, Vegetable Poha, Peanut Chutney, Tomato Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Guava Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Sweet Potato Salad (Veg)', true),
  ('MH', '2026-10-17', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Dondakaya Stir Fry, Chole Curry, Papad, Majiga Pulusu, Avakaya (Mango Pickle), Carrot Halwa, Ghee + Podi', true),
  ('MH', '2026-10-17', 'snacks', 'Punugulu 8 Pcs Medium Size, Groundnut/Coconut Chutney, Cold Badam Milk (1 Medium Glass)', true),
  ('MH', '2026-10-17', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Bendakaya (Bhindi) Pulusu, Vegetable Fried Rice, Gobhi Manchuria, Tomato Sauce, Cabbage Beans Poriyal, Thick Curd, Fruit Custard with Pine Apple (3), and Custard Apple (17, 31), Red Chilli Pickle, Milk + Cofee Powder, Red Lentil Soup', true),
  ('MH', '2026-10-31', 'breakfast', 'Mix Veg Utappam - 2 Pcs Std Size, Vegetable Poha, Peanut Chutney, Tomato Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Guava Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Sweet Potato Salad (Veg)', true),
  ('MH', '2026-10-31', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Dondakaya Stir Fry, Chole Curry, Papad, Majiga Pulusu, Avakaya (Mango Pickle), Carrot Halwa, Ghee + Podi', true),
  ('MH', '2026-10-31', 'snacks', 'Punugulu 8 Pcs Medium Size, Groundnut/Coconut Chutney, Cold Badam Milk (1 Medium Glass)', true),
  ('MH', '2026-10-31', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Bendakaya (Bhindi) Pulusu, Vegetable Fried Rice, Gobhi Manchuria, Tomato Sauce, Cabbage Beans Poriyal, Thick Curd, Fruit Custard with Pine Apple (3), and Custard Apple (17, 31), Red Chilli Pickle, Milk + Cofee Powder, Red Lentil Soup', true),
  ('MH', '2026-10-04', 'breakfast', 'Shavige Bath, Paneer Paratha - 2 Pcs Thin, Coconut Chutney, Thick Curd, Mango Pickle, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Apple + Pomegranate Fresh Juice with Light Sugar, Cornflakes, Egg Bhurji (Non-Veg), Raagi Malt (Veg)', true),
  ('MH', '2026-10-04', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Fry, Chicken Dum Biryani/Paneer Dum Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Triangular Fryums, Nannari Sharbath, Fresh Gongura Chutney, Basundhi (60 ml), Gulab Jamun', true),
  ('MH', '2026-10-04', 'snacks', 'Plum Cake (Egg Less) 1 Big Pc, Masala Tea/Coffee/Milk', true),
  ('MH', '2026-10-04', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Ragi Idly, Groundnut Chutney, Dondakaya Fry, Vegetable Kurma Gravy, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder, Lemon Coriander Soup', true),
  ('MH', '2026-10-18', 'breakfast', 'Shavige Bath, Paneer Paratha - 2 Pcs Thin, Coconut Chutney, Thick Curd, Mango Pickle, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Apple + Pomegranate Fresh Juice with Light Sugar, Cornflakes, Egg Bhurji (Non-Veg), Raagi Malt (Veg)', true),
  ('MH', '2026-10-18', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Fry, Chicken Dum Biryani/Paneer Dum Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Triangular Fryums, Nannari Sharbath, Fresh Gongura Chutney, Basundhi (60 ml), Gulab Jamun', true),
  ('MH', '2026-10-18', 'snacks', 'Plum Cake (Egg Less) 1 Big Pc, Masala Tea/Coffee/Milk', true),
  ('MH', '2026-10-18', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Ragi Idly, Groundnut Chutney, Dondakaya Fry, Vegetable Kurma Gravy, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder, Lemon Coriander Soup', true),
  ('MH', '2026-10-05', 'breakfast', 'Ghee + Veg Pongal, Bhature - 2 Pcs Big, Groundnut Chutney, Sambar, Chole Curry, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Banana Milk Shake with Light Sugar, Cornflakes, Boiled Egg (Non-Veg), Boiled Mixed Beans Salad (Veg)', true),
  ('MH', '2026-10-05', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Tomato Rice, Pesara Punugulu Curry (Pakka Andhra Style), Capsicum Tomato Masala, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Jilebi, Ghee + Podi', true),
  ('MH', '2026-10-05', 'snacks', 'Dry Maggi (Non-Sticky), Tomato Sauce, Tea/Coffee/Milk', true),
  ('MH', '2026-10-05', 'dinner', 'Onions & Lemon Salad, Butter Methi Naan, White Rice, Pesara Pappu, Tomato Rasam, Bhagara Rice, Chicken Mughlai (Non-Veg), Paneer Butter Masala (Veg), Ladies Finger Boiled Fry, Thick Curd, Mixed Fruit Salad, Gongura Pickle, Milk + Cofee Powder, Sweet Corn Soup', true),
  ('MH', '2026-10-19', 'breakfast', 'Ghee + Veg Pongal, Bhature - 2 Pcs Big, Groundnut Chutney, Sambar, Chole Curry, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Banana Milk Shake with Light Sugar, Cornflakes, Boiled Egg (Non-Veg), Boiled Mixed Beans Salad (Veg)', true),
  ('MH', '2026-10-19', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Tomato Rice, Pesara Punugulu Curry (Pakka Andhra Style), Capsicum Tomato Masala, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Jilebi, Ghee + Podi', true),
  ('MH', '2026-10-19', 'snacks', 'Dry Maggi (Non-Sticky), Tomato Sauce, Tea/Coffee/Milk', true),
  ('MH', '2026-10-19', 'dinner', 'Onions & Lemon Salad, Butter Methi Naan, White Rice, Pesara Pappu, Tomato Rasam, Bhagara Rice, Chicken Mughlai (Non-Veg), Paneer Butter Masala (Veg), Ladies Finger Boiled Fry, Thick Curd, Mixed Fruit Salad, Gongura Pickle, Milk + Cofee Powder, Sweet Corn Soup', true),
  ('MH', '2026-10-06', 'breakfast', 'Onion Dosa (6), Masala Dosa (20) - 2 Pcs Std Size, Vada Pav, Coconut Chutney, Mint Chutney, Brown Bread+Peanut Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Pomegranate Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Boiled Soya Chunk Salad (Veg)', true),
  ('MH', '2026-10-06', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Dosakaya Pappu, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Milk Peda, Ghee + Podi', true),
  ('MH', '2026-10-06', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Ginger Tea/Coffee/Milk', true),
  ('MH', '2026-10-06', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Guava Fruit, Tomato Pickle, Milk + Cofee Powder, Brocolli Soup', true),
  ('MH', '2026-10-20', 'breakfast', 'Onion Dosa (6), Masala Dosa (20) - 2 Pcs Std Size, Vada Pav, Coconut Chutney, Mint Chutney, Brown Bread+Peanut Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Pomegranate Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Boiled Soya Chunk Salad (Veg)', true),
  ('MH', '2026-10-20', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Dosakaya Pappu, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Milk Peda, Ghee + Podi', true),
  ('MH', '2026-10-20', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Ginger Tea/Coffee/Milk', true),
  ('MH', '2026-10-20', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Guava Fruit, Tomato Pickle, Milk + Cofee Powder, Brocolli Soup', true),
  ('MH', '2026-10-07', 'breakfast', 'Methi Vada (Big size 3pcs, if not 4pcs), Cucumber Poha, Sambar, Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Papaya Fresh Juice with Light Sugar, Cornflakes, Masala Onion Omlet  (Non-Veg), Greek Yogurt Salad (Veg)', true),
  ('MH', '2026-10-07', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Amaranthus Dal, Pachi Pulusu, Bhagara Rice, Hyderabadi Chicken Curry, Shahi Paneer, Vegetable Jalfrezi, Papad, Butter Milk, Fresh Vegetable Chutney, Badusha', true),
  ('MH', '2026-10-07', 'snacks', 'Onion Soft Pakoda (Less Oily), Tomato Chutney, Tea/Coffee/Milk', true),
  ('MH', '2026-10-07', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Broken Wheat Rava Upma, Coconut Chutney, Bottle Guard Chana Dal Fry, Aloo Mutter Curry, Thick Curd, Mixed Fruit Salad (Pomegranate, Pine Apple, Green grapes), Lemon Pickle, Milk + Cofee Powder, Tomato Soup with Roasted Bread', true),
  ('MH', '2026-10-21', 'breakfast', 'Methi Vada (Big size 3pcs, if not 4pcs), Cucumber Poha, Sambar, Coconut Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Papaya Fresh Juice with Light Sugar, Cornflakes, Masala Onion Omlet  (Non-Veg), Greek Yogurt Salad (Veg)', true),
  ('MH', '2026-10-21', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Amaranthus Dal, Pachi Pulusu, Bhagara Rice, Hyderabadi Chicken Curry, Shahi Paneer, Vegetable Jalfrezi, Papad, Butter Milk, Fresh Vegetable Chutney, Badusha', true),
  ('MH', '2026-10-21', 'snacks', 'Onion Soft Pakoda (Less Oily), Tomato Chutney, Tea/Coffee/Milk', true),
  ('MH', '2026-10-21', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Broken Wheat Rava Upma, Coconut Chutney, Bottle Guard Chana Dal Fry, Aloo Mutter Curry, Thick Curd, Mixed Fruit Salad (Pomegranate, Pine Apple, Green grapes), Lemon Pickle, Milk + Cofee Powder, Tomato Soup with Roasted Bread', true),
  ('MH', '2026-10-08', 'breakfast', 'Poori (3 pcs standard size), Rice Rava Kitchidi, Aloo Basin Chutney, Dal Chutney, Brown Bread+Peanut Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Grapes Fresh Juice with Light Sugar, Museli, Egg Bhurji (Non-Veg), Boiled Paneer Salad (Veg)', true),
  ('MH', '2026-10-08', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Ridge Gourd Dal, Sambar, Pudina Rice, Guthi Vankaya Curry, Kala Chana Masala, Finger Fryums, Lemon Water + Sabja Seeds, Potlakaya Perugu Chutney, Mothichoor Laddu, Ghee + Podi', true),
  ('MH', '2026-10-08', 'snacks', 'Sambar Vada 2 Pcs (Separate), Masala Tea/Coffee/Milk', true),
  ('MH', '2026-10-08', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchurian, Noodles, Tomato Sauce, Chilli Chicken/Malabar Fish Fry (NV), Chilli Paneer/Chilli Babycorn (Veg), Rajma Masala, Thick Curd, Sweet Lime, Ginger Pickle, Milk + Cofee Powder, Creamy Mushroom Soup', true),
  ('MH', '2026-10-22', 'breakfast', 'Poori (3 pcs standard size), Rice Rava Kitchidi, Aloo Basin Chutney, Dal Chutney, Brown Bread+Peanut Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Grapes Fresh Juice with Light Sugar, Museli, Egg Bhurji (Non-Veg), Boiled Paneer Salad (Veg)', true),
  ('MH', '2026-10-22', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Ridge Gourd Dal, Sambar, Pudina Rice, Guthi Vankaya Curry, Kala Chana Masala, Finger Fryums, Lemon Water + Sabja Seeds, Potlakaya Perugu Chutney, Mothichoor Laddu, Ghee + Podi', true),
  ('MH', '2026-10-22', 'snacks', 'Sambar Vada 2 Pcs (Separate), Masala Tea/Coffee/Milk', true),
  ('MH', '2026-10-22', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Fry, Beetroot Tomato Rasam, Veg Manchurian, Noodles, Tomato Sauce, Chilli Chicken/Malabar Fish Fry (NV), Chilli Paneer/Chilli Babycorn (Veg), Rajma Masala, Thick Curd, Sweet Lime, Ginger Pickle, Milk + Cofee Powder, Creamy Mushroom Soup', true),
  ('MH', '2026-10-09', 'breakfast', 'Pesarattu Thin 2 Pcs Std Size, Tomato Suji Upma, Coconut Chutney, Ginger Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Pineapple Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Boiled Chick Peas Salad (Veg)', true),
  ('MH', '2026-10-09', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Cauli Flower Stir Fry (Less Oil), Papad, Lassi, Beerakaya Chutney, Carrot Halwa', true),
  ('MH', '2026-10-09', 'snacks', 'Mysore Bonda 2 Pcs Std Size (Less Oily), Coconut Chutney, Tea/Coffee/Milk', true),
  ('MH', '2026-10-09', 'dinner', 'Onions & Lemon Salad, Beetroot Chapathi (9, 23), White Rice, Dal, Sambar, Kadai Chicken (Non-Veg), Kadai Paneer (Veg), Amritsari Chole, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Fresh Vegetable Chutney/Pickle, Milk + Cofee Powder, Mix Veg Raagi Soup', true),
  ('MH', '2026-10-23', 'breakfast', 'Pesarattu Thin 2 Pcs Std Size, Tomato Suji Upma, Coconut Chutney, Ginger Chutney, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Pineapple Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Boiled Chick Peas Salad (Veg)', true),
  ('MH', '2026-10-23', 'lunch', 'Beetroot & Cucumber Salad, Chapathi, White Rice, Dal Tadka, Rasam, Jeera Rice, Raw Banana Fry, Cauli Flower Stir Fry (Less Oil), Papad, Lassi, Beerakaya Chutney, Carrot Halwa', true),
  ('MH', '2026-10-23', 'snacks', 'Mysore Bonda 2 Pcs Std Size (Less Oily), Coconut Chutney, Tea/Coffee/Milk', true),
  ('MH', '2026-10-23', 'dinner', 'Onions & Lemon Salad, Beetroot Chapathi (9, 23), White Rice, Dal, Sambar, Kadai Chicken (Non-Veg), Kadai Paneer (Veg), Amritsari Chole, Thick Curd, (Watermelon + Muskmelon + Papaya) Cut Fruit, Fresh Vegetable Chutney/Pickle, Milk + Cofee Powder, Mix Veg Raagi Soup', true),
  ('MH', '2026-10-10', 'breakfast', 'Uggani + Mirchi Bajji, Moong Dal Palak Tepla (Hand Made) 2 Pcs, Groundnut Chutney, Onion Tomato Chutney, Brown Bread+Peanut Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Mosambi Fresh Juice with Light Sugar, Cornflakes, Boiled Egg (Non-Veg), Boiled Peanut Sundal (Veg)', true),
  ('MH', '2026-10-10', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Cauli Flower Fry, Chole Curry, Papad, Majjiga Pulusu, Avakaya (Mango Pickle), Chocolate Cake (Egg Less), Ghee + Podi', true),
  ('MH', '2026-10-10', 'snacks', 'Vada Pav 2 Pcs, Mint Sauce, Cold Badam Milk (1 Medium Glass)', true),
  ('MH', '2026-10-10', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Drumstick Sambar, Ghee + Podi + Idly, Coconut Chutney, Tomato Baingan Fry, Thick Curd, Muskmelon Cut Fruit, Red Chilli Pickle, Milk + Cofee Powder, Veg Manchow Soup', true),
  ('MH', '2026-10-24', 'breakfast', 'Uggani + Mirchi Bajji, Moong Dal Palak Tepla (Hand Made) 2 Pcs, Groundnut Chutney, Onion Tomato Chutney, Brown Bread+Peanut Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Mosambi Fresh Juice with Light Sugar, Cornflakes, Boiled Egg (Non-Veg), Boiled Peanut Sundal (Veg)', true),
  ('MH', '2026-10-24', 'lunch', 'Carrot & Cucumber Salad, Pulka, White Rice, Mudda Pappu, Beetroot Tomato Rasam, Pulihora (Tamarind Rice), Cauli Flower Fry, Chole Curry, Papad, Majjiga Pulusu, Avakaya (Mango Pickle), Chocolate Cake (Egg Less), Ghee + Podi', true),
  ('MH', '2026-10-24', 'snacks', 'Vada Pav 2 Pcs, Mint Sauce, Cold Badam Milk (1 Medium Glass)', true),
  ('MH', '2026-10-24', 'dinner', 'Beetroot & Carrot Salad, Roti, White Rice, Dal Maharani, Drumstick Sambar, Ghee + Podi + Idly, Coconut Chutney, Tomato Baingan Fry, Thick Curd, Muskmelon Cut Fruit, Red Chilli Pickle, Milk + Cofee Powder, Veg Manchow Soup', true),
  ('MH', '2026-10-11', 'breakfast', 'Shavige Bath, Mix Veg Paratha (2 Pcs Thin), Groundnut Chutney, Thick Curd, Mango Pickle, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Apple + Pomegranate Fresh Juice with Light Sugar, Museli, Egg Bhurji (Non-Veg), Ragi Malt (Veg)', true),
  ('MH', '2026-10-11', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Makhani, Chicken Fry Piece Biryani/Paneer Fry Piece Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Fryums, Nannari Sharbath, Fresh Gongura Chutney, Vanilla Ice Cream  (Not Frozen Dessert), Gulab Jamun', true),
  ('MH', '2026-10-11', 'snacks', 'Dahi Papdi Chat, Onions, Tea/Coffee/Milk', true),
  ('MH', '2026-10-11', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Karam Dosa (2 Pcs Thin), Coconut Chutney, Dondakaya Fry, Vegetable Kolhapuri, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder, Lemon Coriander Soup', true),
  ('MH', '2026-10-25', 'breakfast', 'Shavige Bath, Mix Veg Paratha (2 Pcs Thin), Groundnut Chutney, Thick Curd, Mango Pickle, White Bread+Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Apple + Pomegranate Fresh Juice with Light Sugar, Museli, Egg Bhurji (Non-Veg), Ragi Malt (Veg)', true),
  ('MH', '2026-10-25', 'lunch', 'Onions & Lemon Salad, Chapathi, White Rice, Dal Makhani, Chicken Fry Piece Biryani/Paneer Fry Piece Biryani, Chicken Thick Gravy / Hyderabadi Mirchi Ka Salan, Onion Raitha, Fryums, Nannari Sharbath, Fresh Gongura Chutney, Vanilla Ice Cream  (Not Frozen Dessert), Gulab Jamun', true),
  ('MH', '2026-10-25', 'snacks', 'Dahi Papdi Chat, Onions, Tea/Coffee/Milk', true),
  ('MH', '2026-10-25', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Pesara Pappu, Sambar, Karam Dosa (2 Pcs Thin), Coconut Chutney, Dondakaya Fry, Vegetable Kolhapuri, Thick Curd, Papaya Cut Fruit, Tomato Pickle, Milk + Cofee Powder, Lemon Coriander Soup', true),
  ('MH', '2026-10-12', 'breakfast', 'Roasted Idli Upma, Bhature - 3 Pcs Big, Coconut Chutney, Chole Curry, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Cold Badam Milk with Light Sugar, Museli, Masala Omlet (Non-Veg), Boiled Red Beans Salad (Veg)', true),
  ('MH', '2026-10-12', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Ghee Rice, Crispy Dragon Potato, Drumstick Tomato Curry, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Mysore Pak, Ghee + Podi', true),
  ('MH', '2026-10-12', 'snacks', 'Chatakedar Corn, Lemon Sauce, Masala Tea/Coffee/Milk', true),
  ('MH', '2026-10-12', 'dinner', 'Onions & Lemon Salad, Butter Methi Naan, White Rice, Dal Tadka, Tomato Rasam, Bhagara Rice, Chettinad Chicken Curry (Non-Veg), Paneer Green Peas Masala (Veg), Bhindi Masala, Thick Curd, Mixed Fruit Salad (Black Grapes, Banana, Pomegranate), Gongura Pickle, Milk + Cofee Powder, Sweet Corn Soup', true),
  ('MH', '2026-10-26', 'breakfast', 'Roasted Idli Upma, Bhature - 3 Pcs Big, Coconut Chutney, Chole Curry, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Cold Badam Milk with Light Sugar, Museli, Masala Omlet (Non-Veg), Boiled Red Beans Salad (Veg)', true),
  ('MH', '2026-10-26', 'lunch', 'Boiled Chana Salad with Onion & Tomato, Chapathi, White Rice, Palak Dal, Sambar, Ghee Rice, Crispy Dragon Potato, Drumstick Tomato Curry, Fryums, Butter Milk, Sorakaya Perugu Chutney, Ghee + Podi, Mysore Pak, Ghee + Podi', true),
  ('MH', '2026-10-26', 'snacks', 'Chatakedar Corn, Lemon Sauce, Masala Tea/Coffee/Milk', true),
  ('MH', '2026-10-26', 'dinner', 'Onions & Lemon Salad, Butter Methi Naan, White Rice, Dal Tadka, Tomato Rasam, Bhagara Rice, Chettinad Chicken Curry (Non-Veg), Paneer Green Peas Masala (Veg), Bhindi Masala, Thick Curd, Mixed Fruit Salad (Black Grapes, Banana, Pomegranate), Gongura Pickle, Milk + Cofee Powder, Sweet Corn Soup', true),
  ('MH', '2026-10-13', 'breakfast', 'Ghee Podi Dosa (2 Pcs Thin), Pav Bhaji, Coconut Chutney, Sambar, Mint Chutney, White Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Pomegranate Fresh Juice with Light Sugar, Museli, Scrambled Egg (Non-Veg), Boiled Soya Bean Salad (Veg)', true),
  ('MH', '2026-10-13', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Amaranthus Dal, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Kalakand, Ghee + Podi', true),
  ('MH', '2026-10-13', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Tea/Coffee/Milk', true),
  ('MH', '2026-10-13', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Sweet Lime, Tomato Pickle, Milk + Cofee Powder, Brocolli Soup', true),
  ('MH', '2026-10-27', 'breakfast', 'Ghee Podi Dosa (2 Pcs Thin), Pav Bhaji, Coconut Chutney, Sambar, Mint Chutney, White Bread+Butter+Jam, Ragi Malt with Salt (1 Medium Glass), Tea/Coffee/Milk, Pomegranate Fresh Juice with Light Sugar, Museli, Scrambled Egg (Non-Veg), Boiled Soya Bean Salad (Veg)', true),
  ('MH', '2026-10-27', 'lunch', 'Carrot & Cucumber Salad, Roti, White Rice, Amaranthus Dal, Beetroot Tomato Rasam, Bisbele Bath, Kakarakaya (Bitter Gourd) Fry, Rajma Masala, Potato Chips, Dahi Vada, Dosakaya Tomato Chutney, Kalakand, Ghee + Podi', true),
  ('MH', '2026-10-27', 'snacks', 'Aloo Samosa 1 Big Pc, Tomato Sauce, Salt Mirchi, Tea/Coffee/Milk', true),
  ('MH', '2026-10-27', 'dinner', 'Beetroot & Carrot Salad, Pulka, White Rice, Dal Makhani, Sambar, Mushroom Biryani, Snake Gourd Poriyal, Aloo Mutter Curry, Thick Curd, Sweet Lime, Tomato Pickle, Milk + Cofee Powder, Brocolli Soup', true),
  ('MH', '2026-10-14', 'breakfast', 'Methu Vada (Big size 3pcs, if not 4pcs), Vegetable Poha, Sambar, Coconut Chutney, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Muskmelon Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Boiled Chick Peas Salad (Veg)', true),
  ('MH', '2026-10-14', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Gongura (Sorrel Leaves) Dal, Sambar, Vegetable Dum Pulav, Andhra Chicken Fry, Kaju Tomato Paneer Fry, Red Beans Curry, Trinagle Fryums, Butter Milk, Coriander + Tomato Chutney, Gulab Jamun', true),
  ('MH', '2026-10-14', 'snacks', 'Bandi Style Ragda Chat, Onion Small pieces, Ginger Tea/Coffee/Milk', true),
  ('MH', '2026-10-14', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Sooji Upma, Coconut Chutney, Bottle Guard Tomato Stir Fry, Soya Chunks Masala, Thick Curd, Green Grapes, Lemon Pickle, Milk + Cofee Powder, Tomato Soup with Roasted Bread', true),
  ('MH', '2026-10-28', 'breakfast', 'Methu Vada (Big size 3pcs, if not 4pcs), Vegetable Poha, Sambar, Coconut Chutney, Brown Bread+Peanut Butter+Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Muskmelon Fresh Juice with Light Sugar, Chocos, Boiled Egg (Non-Veg), Boiled Chick Peas Salad (Veg)', true),
  ('MH', '2026-10-28', 'lunch', 'Onions & Lemon Salad, Palak Roti, White Rice, Gongura (Sorrel Leaves) Dal, Sambar, Vegetable Dum Pulav, Andhra Chicken Fry, Kaju Tomato Paneer Fry, Red Beans Curry, Trinagle Fryums, Butter Milk, Coriander + Tomato Chutney, Gulab Jamun', true),
  ('MH', '2026-10-28', 'snacks', 'Bandi Style Ragda Chat, Onion Small pieces, Ginger Tea/Coffee/Milk', true),
  ('MH', '2026-10-28', 'dinner', 'Beetroot & Carrot Salad, Chapathi, White Rice, Tomato Dal, Rasam, Sooji Upma, Coconut Chutney, Bottle Guard Tomato Stir Fry, Soya Chunks Masala, Thick Curd, Green Grapes, Lemon Pickle, Milk + Cofee Powder, Tomato Soup with Roasted Bread', true),
  ('LH', '2026-10-01', 'breakfast', 'Vegetable Uttapam, Uggani, Peanut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-01', 'lunch', 'Onion Carrot salad, Ajwain Roti, White Rice, Pachi Mirchi Papu, Dosakai sambar, Veg Pulao, Bendi Pulusu, Mix Veg Poriyal, Chips/Fryums/Papad, Curd, Tomato Chutney, Lemon water with Sabja seeds', false),
  ('LH', '2026-10-01', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-01', 'dinner', 'lemon Tea + sabja, Veg Puff', false),
  ('LH', '2026-10-15', 'breakfast', 'Vegetable Uttapam, Uggani, Peanut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-15', 'lunch', 'Onion Carrot salad, Ajwain Roti, White Rice, Pachi Mirchi Papu, Dosakai sambar, Veg Pulao, Bendi Pulusu, Mix Veg Poriyal, Chips/Fryums/Papad, Curd, Tomato Chutney, Lemon water with Sabja seeds', false),
  ('LH', '2026-10-15', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-15', 'dinner', 'lemon Tea + sabja, Veg Puff', false),
  ('LH', '2026-10-29', 'breakfast', 'Vegetable Uttapam, Uggani, Peanut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-29', 'lunch', 'Onion Carrot salad, Ajwain Roti, White Rice, Pachi Mirchi Papu, Dosakai sambar, Veg Pulao, Bendi Pulusu, Mix Veg Poriyal, Chips/Fryums/Papad, Curd, Tomato Chutney, Lemon water with Sabja seeds', false),
  ('LH', '2026-10-29', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-29', 'dinner', 'lemon Tea + sabja, Veg Puff', false),
  ('LH', '2026-10-02', 'breakfast', 'Samiya Bath, Ravva Idly + Karam, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Burji', false),
  ('LH', '2026-10-02', 'lunch', 'Pasta Salad, Phulka, White Rice, Menthikura Papu, Pepper Rasam, Gongura Rice, Raw banana Poriyal, Gobi Matar Curry, Chips/Fryums/Papad, Curd, Chukka Kura Pachadi, Gulab Jam, Nannari with sabja', false),
  ('LH', '2026-10-02', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-02', 'dinner', 'Tea/Coffee/Milk, Aloo Samosa, Tomato sause', false),
  ('LH', '2026-10-16', 'breakfast', 'Samiya Bath, Ravva Idly + Karam, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Burji', false),
  ('LH', '2026-10-16', 'lunch', 'Pasta Salad, Phulka, White Rice, Menthikura Papu, Pepper Rasam, Gongura Rice, Raw banana Poriyal, Gobi Matar Curry, Chips/Fryums/Papad, Curd, Chukka Kura Pachadi, Gulab Jam, Nannari with sabja', false),
  ('LH', '2026-10-16', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-16', 'dinner', 'Tea/Coffee/Milk, Aloo Samosa, Tomato sause', false),
  ('LH', '2026-10-30', 'breakfast', 'Samiya Bath, Ravva Idly + Karam, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Burji', false),
  ('LH', '2026-10-30', 'lunch', 'Pasta Salad, Phulka, White Rice, Menthikura Papu, Pepper Rasam, Gongura Rice, Raw banana Poriyal, Gobi Matar Curry, Chips/Fryums/Papad, Curd, Chukka Kura Pachadi, Gulab Jam, Nannari with sabja', false),
  ('LH', '2026-10-30', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-30', 'dinner', 'Tea/Coffee/Milk, Aloo Samosa, Tomato sause', false),
  ('LH', '2026-10-03', 'breakfast', 'Mysore Bonda, Wheat Upma (With veggies), Peanut Chilli Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Ragi malt (Salt), Boiled Egg', false),
  ('LH', '2026-10-03', 'lunch', 'Sweet Corn salad, Methi Roti, White Rice, Dal Makhani, Pachi Pulusu, Aloo Ka Tehri, Sorakaya Chenna Curry, Dondayaya Fry, Chips/Fryums/Papad, Curd, Mango Pachadi, Butter Milk, Lemon water with Sabja seeds, Gulab Jamun', false),
  ('LH', '2026-10-03', 'snacks', 'North Style, Home Style, Home Style', false),
  ('LH', '2026-10-03', 'dinner', 'Tea/Coffee/Milk, Dahi Papdi chaat, Pudina Chutney, Sweet Tamrind Chutney, Sev+ Onion, Tomato+Chaat Masala', false),
  ('LH', '2026-10-17', 'breakfast', 'Mysore Bonda, Wheat Upma (With veggies), Peanut Chilli Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Ragi malt (Salt), Boiled Egg', false),
  ('LH', '2026-10-17', 'lunch', 'Sweet Corn salad, Methi Roti, White Rice, Dal Makhani, Pachi Pulusu, Aloo Ka Tehri, Sorakaya Chenna Curry, Dondayaya Fry, Chips/Fryums/Papad, Curd, Mango Pachadi, Butter Milk, Lemon water with Sabja seeds, Gulab Jamun', false),
  ('LH', '2026-10-17', 'snacks', 'North Style, Home Style, Home Style', false),
  ('LH', '2026-10-17', 'dinner', 'Tea/Coffee/Milk, Dahi Papdi chaat, Pudina Chutney, Sweet Tamrind Chutney, Sev+ Onion, Tomato+Chaat Masala', false),
  ('LH', '2026-10-24', 'breakfast', 'Mysore Bonda, Wheat Upma (With veggies), Peanut Chilli Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Ragi malt (Salt), Boiled Egg', false),
  ('LH', '2026-10-24', 'lunch', 'Sweet Corn salad, Methi Roti, White Rice, Dal Makhani, Pachi Pulusu, Aloo Ka Tehri, Sorakaya Chenna Curry, Dondayaya Fry, Chips/Fryums/Papad, Curd, Mango Pachadi, Butter Milk, Lemon water with Sabja seeds, Gulab Jamun', false),
  ('LH', '2026-10-24', 'snacks', 'North Style, Home Style, Home Style', false),
  ('LH', '2026-10-24', 'dinner', 'Tea/Coffee/Milk, Dahi Papdi chaat, Pudina Chutney, Sweet Tamrind Chutney, Sev+ Onion, Tomato+Chaat Masala', false),
  ('LH', '2026-10-04', 'breakfast', 'Tomato Bath, Coconut Chutney, Aloo Paratha + Pickle + curd, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Vegetable Scrambled Egg', false),
  ('LH', '2026-10-04', 'lunch', 'Onion Lemon Salad, Phulka, Thotakura Papu, Chicken gravy, Hyderabadi Chicken Dum Biryani, Hyderabadi Paneer Dum Biryani, Mirchi Ka Salan, Raita, Curd, Gongura Pachadi, Ice Cream, Butter Milk, Lemon water with Sabja seeds', false),
  ('LH', '2026-10-04', 'snacks', 'Home Style', false),
  ('LH', '2026-10-04', 'dinner', 'Tea/Coffee/Milk, Sambar Vada', false),
  ('LH', '2026-10-18', 'breakfast', 'Tomato Bath, Coconut Chutney, Aloo Paratha + Pickle + curd, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Vegetable Scrambled Egg', false),
  ('LH', '2026-10-18', 'lunch', 'Onion Lemon Salad, Phulka, Thotakura Papu, Chicken gravy, Hyderabadi Chicken Dum Biryani, Hyderabadi Paneer Dum Biryani, Mirchi Ka Salan, Raita, Curd, Gongura Pachadi, Ice Cream, Butter Milk, Lemon water with Sabja seeds', false),
  ('LH', '2026-10-18', 'snacks', 'Home Style', false),
  ('LH', '2026-10-18', 'dinner', 'Tea/Coffee/Milk, Sambar Vada', false),
  ('LH', '2026-10-05', 'breakfast', 'Ven Pongal ( kara pongal), Neer Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette', false),
  ('LH', '2026-10-05', 'lunch', 'Creamy Coleslaw, Methi Roti, White Rice, Tomato Dal, Drumstick Sambar, Tomato Rice, Kadai Kofta Curry, Cabbage Carrot Poriyal, Chips/Fryums/Papad, Curd, Pudina tomato Chutney, Bellam Jilebi
Butter Milk, Lemon water with Sabja Seeds', false),
  ('LH', '2026-10-05', 'snacks', 'North Style, Home Style, Home Style', false),
  ('LH', '2026-10-05', 'dinner', 'Tea/Coffee/Milk, Veg Roll, (Onion, cabbge, capsicum & Carrot), Sauce/Chutney', false),
  ('LH', '2026-10-19', 'breakfast', 'Ven Pongal ( kara pongal), Neer Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette', false),
  ('LH', '2026-10-19', 'lunch', 'Creamy Coleslaw, Methi Roti, White Rice, Tomato Dal, Drumstick Sambar, Tomato Rice, Kadai Kofta Curry, Cabbage Carrot Poriyal, Chips/Fryums/Papad, Curd, Pudina tomato Chutney, Bellam Jilebi
Butter Milk, Lemon water with Sabja Seeds', false),
  ('LH', '2026-10-19', 'snacks', 'North Style, Home Style, Home Style', false),
  ('LH', '2026-10-19', 'dinner', 'Tea/Coffee/Milk, Veg Roll, (Onion, cabbge, capsicum & Carrot), Sauce/Chutney', false),
  ('LH', '2026-10-06', 'breakfast', 'Masala Dosa, Mix VegUggani, Peanut Dry Mirchi Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Pepper Fry', false),
  ('LH', '2026-10-06', 'lunch', 'Tossed Vegetable Salad (Beans, Carrot, peanuts etc...), Methi Roti, White Rice, Gongura Dal, Mullangi Sambar, Aloo 65 Rice, Mulakada Tomato Curry, Gobi Peas Poriyal, Chips/Fryums/Papad, Curd, Beerakai Pachdi', false),
  ('LH', '2026-10-06', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-06', 'dinner', 'Tea/Coffee/Milk, Soupy Mix veg Maggie, (Carrot, Chilli, Beans, Coriander)', false),
  ('LH', '2026-10-20', 'breakfast', 'Masala Dosa, Mix VegUggani, Peanut Dry Mirchi Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Pepper Fry', false),
  ('LH', '2026-10-20', 'lunch', 'Tossed Vegetable Salad (Beans, Carrot, peanuts etc...), Methi Roti, White Rice, Gongura Dal, Mullangi Sambar, Aloo 65 Rice, Mulakada Tomato Curry, Gobi Peas Poriyal, Chips/Fryums/Papad, Curd, Beerakai Pachdi', false),
  ('LH', '2026-10-20', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-20', 'dinner', 'Tea/Coffee/Milk, Soupy Mix veg Maggie, (Carrot, Chilli, Beans, Coriander)', false),
  ('LH', '2026-10-07', 'breakfast', 'Sabudana Kichidi, Moondal Chilla, Peanut Chutney, Green Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-07', 'lunch', 'Vegetable Salad, Carrot Roti, White Rice, Bachalkura Papu, Papu Charu, Chilli Coconut Rice, Hariyali Chicken Curry, Shahi Paneer Curry, Curd, Sorakai Pachadi, Double Ka Meeta
Butter Milk, lemon water with sabja seeds', false),
  ('LH', '2026-10-07', 'snacks', 'Indian, North Style, Home Style', false),
  ('LH', '2026-10-07', 'dinner', 'Tea/Coffee/Milk, Mix Veg Cutlet (2 Pcs) - Med size, Tomato sause', false),
  ('LH', '2026-10-21', 'breakfast', 'Sabudana Kichidi, Moondal Chilla, Peanut Chutney, Green Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-21', 'lunch', 'Vegetable Salad, Carrot Roti, White Rice, Bachalkura Papu, Papu Charu, Chilli Coconut Rice, Hariyali Chicken Curry, Shahi Paneer Curry, Curd, Sorakai Pachadi, Double Ka Meeta
Butter Milk, lemon water with sabja seeds', false),
  ('LH', '2026-10-21', 'snacks', 'Indian, North Style, Home Style', false),
  ('LH', '2026-10-21', 'dinner', 'Tea/Coffee/Milk, Mix Veg Cutlet (2 Pcs) - Med size, Tomato sause', false),
  ('LH', '2026-10-08', 'breakfast', 'Elluli Karam  Dosa, Poha, Coconut Chutney, Vegetable Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Scrambled egg', false),
  ('LH', '2026-10-08', 'lunch', 'Chickpea salad (Chickpeas, Cucumber, Saute tomato, Lemon), Palak Roti, White Rice, Dosakai Tomato Papu, Chamagada Charu, Burnt Garlic chilli Jeera Rice, Aloo Brinjal Poriyal, Rajma Masala Curry, Chips/Fryums/Papad, Curd, Kobbari Pudina Pachadi', false),
  ('LH', '2026-10-08', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-08', 'dinner', 'Tea/Coffee/Milk, Masala Pesara Vada, Fresh Tomato Chilli Chutney', false),
  ('LH', '2026-10-22', 'breakfast', 'Elluli Karam  Dosa, Poha, Coconut Chutney, Vegetable Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Scrambled egg', false),
  ('LH', '2026-10-22', 'lunch', 'Chickpea salad (Chickpeas, Cucumber, Saute tomato, Lemon), Palak Roti, White Rice, Dosakai Tomato Papu, Chamagada Charu, Burnt Garlic chilli Jeera Rice, Aloo Brinjal Poriyal, Rajma Masala Curry, Chips/Fryums/Papad, Curd, Kobbari Pudina Pachadi', false),
  ('LH', '2026-10-22', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-22', 'dinner', 'Tea/Coffee/Milk, Masala Pesara Vada, Fresh Tomato Chilli Chutney', false),
  ('LH', '2026-10-09', 'breakfast', 'Vada, Vegetable dalia, Fried Channa Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Omlete', false),
  ('LH', '2026-10-09', 'lunch', 'Potato Peas salad, Butter Roti, White Rice, Thotakura Papu, Mix veg Charu, Palak rice, Beerakai Tomato Curry, Cabbage Chana Poriyal, Chips/Fryums/Papad, Curd, Kothimera Dosakai Pachadi, Kala Jamun
Butter milk, lemon water with sabja seeds', false),
  ('LH', '2026-10-09', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-09', 'dinner', 'lemon Tea + sabja, Pani Puri', false),
  ('LH', '2026-10-23', 'breakfast', 'Vada, Vegetable dalia, Fried Channa Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Omlete', false),
  ('LH', '2026-10-23', 'lunch', 'Potato Peas salad, Butter Roti, White Rice, Thotakura Papu, Mix veg Charu, Palak rice, Beerakai Tomato Curry, Cabbage Chana Poriyal, Chips/Fryums/Papad, Curd, Kothimera Dosakai Pachadi, Kala Jamun
Butter milk, lemon water with sabja seeds', false),
  ('LH', '2026-10-23', 'snacks', 'Home Style, North Style, Home Style', false),
  ('LH', '2026-10-23', 'dinner', 'lemon Tea + sabja, Pani Puri', false),
  ('LH', '2026-10-10', 'breakfast', 'Chole bhature, Mix Veg Poha, Tomato chutney, Cholle Channa Curry, Bread + Butter + Jam, Sprouts (1 small cup)
Ragi Malt (Salt), Tea/Coffee/Milk, Egg Pepper Fry', false),
  ('LH', '2026-10-10', 'lunch', 'Cucumbar Yogurt Salad, Ghee Roti, White Rice, Moongdal tadka, Andhra Style Sambar, Mint Onion Pulao, Bendakai Masala Curry, Aloo 65, Chips/Fryums/Papad, Curd, Tomato Brinjal Pachadi', false),
  ('LH', '2026-10-10', 'snacks', 'Home Style, Deep Fry, Home Style', false),
  ('LH', '2026-10-10', 'dinner', 'Hot Chocolate, Chocolate Eggless Cake', false),
  ('LH', '2026-10-31', 'breakfast', 'Chole bhature, Mix Veg Poha, Tomato chutney, Cholle Channa Curry, Bread + Butter + Jam, Sprouts (1 small cup)
Ragi Malt (Salt), Tea/Coffee/Milk, Egg Pepper Fry', false),
  ('LH', '2026-10-31', 'lunch', 'Cucumbar Yogurt Salad, Ghee Roti, White Rice, Moongdal tadka, Andhra Style Sambar, Mint Onion Pulao, Bendakai Masala Curry, Aloo 65, Chips/Fryums/Papad, Curd, Tomato Brinjal Pachadi', false),
  ('LH', '2026-10-31', 'snacks', 'Home Style, Deep Fry, Home Style', false),
  ('LH', '2026-10-31', 'dinner', 'Hot Chocolate, Chocolate Eggless Cake', false),
  ('LH', '2026-10-11', 'breakfast', 'Veg Kitchidi, Gobi Paratha + Pickle + Curd, Peanut  Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-11', 'lunch', 'Onion Lemon Salad, Phulka, Pappulusu, Chicken gravy, Chicken Fry peice Biryani, Chatpata Paneer Biryani
Mirchi Ka salan
Raitha, Curd, Gongura Pachadi, Ice Cream, Butter Milk, Lemon water with Sabja seeds', false),
  ('LH', '2026-10-11', 'dinner', 'Tea/Coffee/Milk, Vada Pav, Fresh Tomato Chilli Chutney', false),
  ('LH', '2026-10-25', 'breakfast', 'Veg Kitchidi, Gobi Paratha + Pickle + Curd, Peanut  Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-25', 'lunch', 'Onion Lemon Salad, Phulka, Pappulusu, Chicken gravy, Chicken Fry peice Biryani, Chatpata Paneer Biryani
Mirchi Ka salan
Raitha, Curd, Gongura Pachadi, Ice Cream, Butter Milk, Lemon water with Sabja seeds', false),
  ('LH', '2026-10-25', 'dinner', 'Tea/Coffee/Milk, Vada Pav, Fresh Tomato Chilli Chutney', false),
  ('LH', '2026-10-12', 'breakfast', 'Semiya Bath, MasalA Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette', false),
  ('LH', '2026-10-12', 'lunch', 'Cucumbar carrot Salad, Butter Roti, White Rice, Palak Dal, Kothimeera Rasam, Karvepaku karam Rice, Brinjal Tomato Curry, Chilli Jeera Aloo Poriyal, Chips/Fryums/Papad, Curd, Tomato & Dosakai vankai mukkala pachadi, Boondi Sweet', false),
  ('LH', '2026-10-12', 'snacks', 'Home Style, Boiled & Cook, Home Style', false),
  ('LH', '2026-10-12', 'dinner', 'Tea/Coffee/Milk, Soupy Mix veg Maggie (Carrot, Chilli, Beans, Coriander)', false),
  ('LH', '2026-10-26', 'breakfast', 'Semiya Bath, MasalA Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette', false),
  ('LH', '2026-10-26', 'lunch', 'Cucumbar carrot Salad, Butter Roti, White Rice, Palak Dal, Kothimeera Rasam, Karvepaku karam Rice, Brinjal Tomato Curry, Chilli Jeera Aloo Poriyal, Chips/Fryums/Papad, Curd, Tomato & Dosakai vankai mukkala pachadi, Boondi Sweet', false),
  ('LH', '2026-10-26', 'snacks', 'Home Style, Boiled & Cook, Home Style', false),
  ('LH', '2026-10-26', 'dinner', 'Tea/Coffee/Milk, Soupy Mix veg Maggie (Carrot, Chilli, Beans, Coriander)', false),
  ('LH', '2026-10-13', 'breakfast', 'Veg Pongal, vada, Dal Red chilli Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-13', 'lunch', 'Kosambari Moongdal (Roasted Peanuts, Pomogranate, corriender, grated coconut), Ghee Roti, White Rice, Dal Tadka, Vankaya Charu, Achaar Rice, Beerkai Ullipai Curry, Bendi Pakodi, Chips/Fryums/Papad, Curd, Vankai Pachadi', false),
  ('LH', '2026-10-13', 'snacks', 'Indian, Deep Fry, Home Style', false),
  ('LH', '2026-10-13', 'dinner', 'Tea/Coffee/Milk, Dal Kachori, Pudina Chutney & Sweet Tamrind Chutney', false),
  ('LH', '2026-10-27', 'breakfast', 'Veg Pongal, vada, Dal Red chilli Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg', false),
  ('LH', '2026-10-27', 'lunch', 'Kosambari Moongdal (Roasted Peanuts, Pomogranate, corriender, grated coconut), Ghee Roti, White Rice, Dal Tadka, Vankaya Charu, Achaar Rice, Beerkai Ullipai Curry, Bendi Pakodi, Chips/Fryums/Papad, Curd, Vankai Pachadi', false),
  ('LH', '2026-10-27', 'snacks', 'Indian, Deep Fry, Home Style', false),
  ('LH', '2026-10-27', 'dinner', 'Tea/Coffee/Milk, Dal Kachori, Pudina Chutney & Sweet Tamrind Chutney', false),
  ('LH', '2026-10-14', 'breakfast', 'Onion Pesarattu, Tomato Bath, Ginger Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Scrambled Egg', false),
  ('LH', '2026-10-14', 'lunch', 'Vegetable Salad, Beetroot Roti, White Rice, Palak Dal, Mix veg Sambar, Vaangi bath, Kodi Iguru, Kadai Paneer Curry, Curd, Garlic Chutney, Kaja

Butter Milk, Lemon water with sabja seeds', false),
  ('LH', '2026-10-14', 'snacks', 'Andhra Home Style, North Style, Home Style', false),
  ('LH', '2026-10-14', 'dinner', 'Tea/Coffee/Milk, onion Corn Samosa (Big Size), Sauce/Chutney', false),
  ('LH', '2026-10-28', 'breakfast', 'Onion Pesarattu, Tomato Bath, Ginger Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Scrambled Egg', false),
  ('LH', '2026-10-28', 'lunch', 'Vegetable Salad, Beetroot Roti, White Rice, Palak Dal, Mix veg Sambar, Vaangi bath, Kodi Iguru, Kadai Paneer Curry, Curd, Garlic Chutney, Kaja

Butter Milk, Lemon water with sabja seeds', false),
  ('LH', '2026-10-28', 'snacks', 'Andhra Home Style, North Style, Home Style', false),
  ('LH', '2026-10-28', 'dinner', 'Tea/Coffee/Milk, onion Corn Samosa (Big Size), Sauce/Chutney', false),
  ('LH', '2026-10-01', 'breakfast', 'Vegetable Uttapam, Uggani, Peanut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Corn Flakes, Boiled Paneer Cubes', true),
  ('LH', '2026-10-01', 'lunch', 'Onion Carrot salad, Ajwain Roti, White Rice, Pachi Mirchi Papu, Dosakai sambar, Veg Pulao, Bendi Pulusu, Mix Veg Poriyal, Chips/Fryums/Papad, Curd, Tomato Chutney, Gulab Jamun', true),
  ('LH', '2026-10-01', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-01', 'dinner', 'lemon Tea + sabja, Veg Puff', true),
  ('LH', '2026-10-15', 'breakfast', 'Vegetable Uttapam, Uggani, Peanut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Corn Flakes, Boiled Paneer Cubes', true),
  ('LH', '2026-10-15', 'lunch', 'Onion Carrot salad, Ajwain Roti, White Rice, Pachi Mirchi Papu, Dosakai sambar, Veg Pulao, Bendi Pulusu, Mix Veg Poriyal, Chips/Fryums/Papad, Curd, Tomato Chutney, Gulab Jamun', true),
  ('LH', '2026-10-15', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-15', 'dinner', 'lemon Tea + sabja, Veg Puff', true),
  ('LH', '2026-10-29', 'breakfast', 'Vegetable Uttapam, Uggani, Peanut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Corn Flakes, Boiled Paneer Cubes', true),
  ('LH', '2026-10-29', 'lunch', 'Onion Carrot salad, Ajwain Roti, White Rice, Pachi Mirchi Papu, Dosakai sambar, Veg Pulao, Bendi Pulusu, Mix Veg Poriyal, Chips/Fryums/Papad, Curd, Tomato Chutney, Gulab Jamun', true),
  ('LH', '2026-10-29', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-29', 'dinner', 'lemon Tea + sabja, Veg Puff', true),
  ('LH', '2026-10-02', 'breakfast', 'Samiya Bath, Ravva Idly + Karam, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Burji, Fresh Fruit Juice, #ERROR!, #ERROR!', true),
  ('LH', '2026-10-02', 'lunch', 'Pasta Salad, Phulka, White Rice, Menthikura Papu, Pepper Rasam, Gongura Rice, Raw banana Poriyal, Gobi Matar Curry, Chips/Fryums/Papad, Curd, Chukka Kura Pachadi, Rasmalai', true),
  ('LH', '2026-10-02', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-02', 'dinner', 'Tea/Coffee/Milk, Aloo Samosa, Tomato sause', true),
  ('LH', '2026-10-16', 'breakfast', 'Samiya Bath, Ravva Idly + Karam, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Burji, Fresh Fruit Juice, #ERROR!, #ERROR!', true),
  ('LH', '2026-10-16', 'lunch', 'Pasta Salad, Phulka, White Rice, Menthikura Papu, Pepper Rasam, Gongura Rice, Raw banana Poriyal, Gobi Matar Curry, Chips/Fryums/Papad, Curd, Chukka Kura Pachadi, Rasmalai', true),
  ('LH', '2026-10-16', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-16', 'dinner', 'Tea/Coffee/Milk, Aloo Samosa, Tomato sause', true),
  ('LH', '2026-10-30', 'breakfast', 'Samiya Bath, Ravva Idly + Karam, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Burji, Fresh Fruit Juice, #ERROR!, #ERROR!', true),
  ('LH', '2026-10-30', 'lunch', 'Pasta Salad, Phulka, White Rice, Menthikura Papu, Pepper Rasam, Gongura Rice, Raw banana Poriyal, Gobi Matar Curry, Chips/Fryums/Papad, Curd, Chukka Kura Pachadi, Rasmalai', true),
  ('LH', '2026-10-30', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-30', 'dinner', 'Tea/Coffee/Milk, Aloo Samosa, Tomato sause', true),
  ('LH', '2026-10-03', 'breakfast', 'Mysore Bonda, Wheat Upma (with veggies), Peanut Chilli Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Ragi malt (Salt), Boiled Egg, Fresh Fruit Juice, Chocos, Boiled Chick Peas', true),
  ('LH', '2026-10-03', 'lunch', 'Sweet Corn salad, Methi Roti, White Rice, Dal Makhani, Pachi Pulusu, Aloo Ka Tehri, Sorakaya Chenna Curry, Dondayaya Fry, Chips/Fryums/Papad, Curd, Mango Pachadi, Kalajamun', true),
  ('LH', '2026-10-03', 'snacks', 'North Style, Home Style, Home Style', true),
  ('LH', '2026-10-03', 'dinner', 'Tea/Coffee/Milk, Dahi Papdi chaat, Pudina Chutney, Sweet Tamrind Chutney, Sev+ Onion, Tomato+Chaat Masala', true),
  ('LH', '2026-10-17', 'breakfast', 'Mysore Bonda, Wheat Upma (with veggies), Peanut Chilli Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Ragi malt (Salt), Boiled Egg, Fresh Fruit Juice, Chocos, Boiled Chick Peas', true),
  ('LH', '2026-10-17', 'lunch', 'Sweet Corn salad, Methi Roti, White Rice, Dal Makhani, Pachi Pulusu, Aloo Ka Tehri, Sorakaya Chenna Curry, Dondayaya Fry, Chips/Fryums/Papad, Curd, Mango Pachadi, Kalajamun', true),
  ('LH', '2026-10-17', 'snacks', 'North Style, Home Style, Home Style', true),
  ('LH', '2026-10-17', 'dinner', 'Tea/Coffee/Milk, Dahi Papdi chaat, Pudina Chutney, Sweet Tamrind Chutney, Sev+ Onion, Tomato+Chaat Masala', true),
  ('LH', '2026-10-24', 'breakfast', 'Mysore Bonda, Wheat Upma (with veggies), Peanut Chilli Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Ragi malt (Salt), Boiled Egg, Fresh Fruit Juice, Chocos, Boiled Chick Peas', true),
  ('LH', '2026-10-24', 'lunch', 'Sweet Corn salad, Methi Roti, White Rice, Dal Makhani, Pachi Pulusu, Aloo Ka Tehri, Sorakaya Chenna Curry, Dondayaya Fry, Chips/Fryums/Papad, Curd, Mango Pachadi, Kalajamun', true),
  ('LH', '2026-10-24', 'snacks', 'North Style, Home Style, Home Style', true),
  ('LH', '2026-10-24', 'dinner', 'Tea/Coffee/Milk, Dahi Papdi chaat, Pudina Chutney, Sweet Tamrind Chutney, Sev+ Onion, Tomato+Chaat Masala', true),
  ('LH', '2026-10-04', 'breakfast', 'Tomato Bath, Coconut Chutney, Aloo Paratha + Pickle + curd, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Vegetable Scrambled Egg, Fresh Fruit Juice, Musli, Paneer Burji', true),
  ('LH', '2026-10-04', 'lunch', 'Onion Lemon Salad, Phulka, Thotakura Papu, Chicken gravy, Hyderabadi Chicken Dum Biryani, Hyderabadi Paneer Dum Biryani, Mirchi Ka Salan, Raita, Curd, Gongura Pachadi, Ice Cream', true),
  ('LH', '2026-10-04', 'snacks', 'Home Style', true),
  ('LH', '2026-10-04', 'dinner', 'Tea/Coffee/Milk, Sambar Vada', true),
  ('LH', '2026-10-18', 'breakfast', 'Tomato Bath, Coconut Chutney, Aloo Paratha + Pickle + curd, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Vegetable Scrambled Egg, Fresh Fruit Juice, Musli, Paneer Burji', true),
  ('LH', '2026-10-18', 'lunch', 'Onion Lemon Salad, Phulka, Thotakura Papu, Chicken gravy, Hyderabadi Chicken Dum Biryani, Hyderabadi Paneer Dum Biryani, Mirchi Ka Salan, Raita, Curd, Gongura Pachadi, Ice Cream', true),
  ('LH', '2026-10-18', 'snacks', 'Home Style', true),
  ('LH', '2026-10-18', 'dinner', 'Tea/Coffee/Milk, Sambar Vada', true),
  ('LH', '2026-10-05', 'breakfast', 'Ven Pongal ( kara pongal), Neer Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette, Fresh Fruit Juice, Corn Flakes, Peanut Sandals', true),
  ('LH', '2026-10-05', 'lunch', 'Creamy Coleslaw, Missi Roti, White Rice, Tomato Dal, Drumstick Sambar, Tomato Rice, Kadai Kofta Curry, Cabbage Carrot Poriyal, Chips/Fryums/Papad, Curd, Pudina tomato Chutney, Bellam Jilebi', true),
  ('LH', '2026-10-05', 'snacks', 'North Style, Home Style, Home Style', true),
  ('LH', '2026-10-05', 'dinner', 'Tea/Coffee/Milk, Veg Roll, (Onion, cabbge, capsicum & Carrot), Sauce/Chutney', true),
  ('LH', '2026-10-19', 'breakfast', 'Ven Pongal ( kara pongal), Neer Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette, Fresh Fruit Juice, Corn Flakes, Peanut Sandals', true),
  ('LH', '2026-10-19', 'lunch', 'Creamy Coleslaw, Missi Roti, White Rice, Tomato Dal, Drumstick Sambar, Tomato Rice, Kadai Kofta Curry, Cabbage Carrot Poriyal, Chips/Fryums/Papad, Curd, Pudina tomato Chutney, Bellam Jilebi', true),
  ('LH', '2026-10-19', 'snacks', 'North Style, Home Style, Home Style', true),
  ('LH', '2026-10-19', 'dinner', 'Tea/Coffee/Milk, Veg Roll, (Onion, cabbge, capsicum & Carrot), Sauce/Chutney', true),
  ('LH', '2026-10-06', 'breakfast', 'Masala Dosa, Mix VegUggani, Peanut Dry Mirchi Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Pepper Fry, Fresh Fruit Juice, Chocos, Boiled Paneer Cubes', true),
  ('LH', '2026-10-06', 'lunch', 'Tossed Vegetable Salad (Beans, Carrot, peanuts etc...), Methi Roti, White Rice, Gongura Dal, Mullangi Sambar, Peas Pulao, Mulakada Tomato Curry, Gobi Peas Poriyal, Chips/Fryums/Papad, Curd, Beerakai Pachdi, Motichoor laddu', true),
  ('LH', '2026-10-06', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-06', 'dinner', 'Tea/Coffee/Milk, Dry Maggie, (Carrot, Chilli, Beans, Coriander)', true),
  ('LH', '2026-10-20', 'breakfast', 'Masala Dosa, Mix VegUggani, Peanut Dry Mirchi Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Egg Pepper Fry, Fresh Fruit Juice, Chocos, Boiled Paneer Cubes', true),
  ('LH', '2026-10-20', 'lunch', 'Tossed Vegetable Salad (Beans, Carrot, peanuts etc...), Methi Roti, White Rice, Gongura Dal, Mullangi Sambar, Peas Pulao, Mulakada Tomato Curry, Gobi Peas Poriyal, Chips/Fryums/Papad, Curd, Beerakai Pachdi, Motichoor laddu', true),
  ('LH', '2026-10-20', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-20', 'dinner', 'Tea/Coffee/Milk, Dry Maggie, (Carrot, Chilli, Beans, Coriander)', true),
  ('LH', '2026-10-07', 'breakfast', 'Sabudana Kichidi, Moondal Chilla, Peanut Chutney, Green Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Corn Flakes, Boiled Chick Peas', true),
  ('LH', '2026-10-07', 'lunch', 'Vegetable Salad, Carrot Roti, White Rice, Bachalkura Papu, Papu Charu, Chilli Coconut Rice, Hariyali Chicken Curry, Shahi Paneer Curry, Curd, Sorakai Pachadi, Double Ka Meeta', true),
  ('LH', '2026-10-07', 'snacks', 'Indian, North Style, Home Style', true),
  ('LH', '2026-10-07', 'dinner', 'Tea/Coffee/Milk, Mix Veg Cutlet (2 Pcs) - Med size, Tomato sause', true),
  ('LH', '2026-10-21', 'breakfast', 'Sabudana Kichidi, Moondal Chilla, Peanut Chutney, Green Chutney, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Corn Flakes, Boiled Chick Peas', true),
  ('LH', '2026-10-21', 'lunch', 'Vegetable Salad, Carrot Roti, White Rice, Bachalkura Papu, Papu Charu, Chilli Coconut Rice, Hariyali Chicken Curry, Shahi Paneer Curry, Curd, Sorakai Pachadi, Double Ka Meeta', true),
  ('LH', '2026-10-21', 'snacks', 'Indian, North Style, Home Style', true),
  ('LH', '2026-10-21', 'dinner', 'Tea/Coffee/Milk, Mix Veg Cutlet (2 Pcs) - Med size, Tomato sause', true),
  ('LH', '2026-10-08', 'breakfast', 'Elluli Karam  Dosa, Poha, Coconut Chutney, Vegetable Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Scrambled egg, Fresh Fruit Juice, Museli, Paneer Burji', true),
  ('LH', '2026-10-08', 'lunch', 'Chickpea salad (Chickpeas, Cucumber, Saute tomato, Lemon), Palak Roti, White Rice, Dosakai Tomato Papu, Chamagada Charu, Burnt Garlic chilli Jeera Rice, Aloo Brinjal Poriyal, Rajma Masala Curry, Chips/Fryums/Papad, Curd, Kobbari Pudina Pachadi, Semiya payasam', true),
  ('LH', '2026-10-08', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-08', 'dinner', 'Tea/Coffee/Milk, Masala Pesara Vada, Fresh Tomato Chilli Chutney', true),
  ('LH', '2026-10-22', 'breakfast', 'Elluli Karam  Dosa, Poha, Coconut Chutney, Vegetable Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Scrambled egg, Fresh Fruit Juice, Museli, Paneer Burji', true),
  ('LH', '2026-10-22', 'lunch', 'Chickpea salad (Chickpeas, Cucumber, Saute tomato, Lemon), Palak Roti, White Rice, Dosakai Tomato Papu, Chamagada Charu, Burnt Garlic chilli Jeera Rice, Aloo Brinjal Poriyal, Rajma Masala Curry, Chips/Fryums/Papad, Curd, Kobbari Pudina Pachadi, Semiya payasam', true),
  ('LH', '2026-10-22', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-22', 'dinner', 'Tea/Coffee/Milk, Masala Pesara Vada, Fresh Tomato Chilli Chutney', true),
  ('LH', '2026-10-09', 'breakfast', 'Vada, Vegetable dalia, Fried Channa Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Omlete, Fresh Fruit Juice, Corn Flakes, Boiled Paneer Cubes', true),
  ('LH', '2026-10-09', 'lunch', 'Potato Peas salad, Butter Roti, White Rice, Thotakura Papu, Mix veg Charu, Palak rice, Beerakai Tomato Curry, Cabbage Chana Poriyal, Chips/Fryums/Papad, Curd, Kothimera Dosakai Pachadi, Kala Jamun', true),
  ('LH', '2026-10-09', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-09', 'dinner', 'lemon Tea + sabja, Pani Puri', true),
  ('LH', '2026-10-23', 'breakfast', 'Vada, Vegetable dalia, Fried Channa Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Omlete, Fresh Fruit Juice, Corn Flakes, Boiled Paneer Cubes', true),
  ('LH', '2026-10-23', 'lunch', 'Potato Peas salad, Butter Roti, White Rice, Thotakura Papu, Mix veg Charu, Palak rice, Beerakai Tomato Curry, Cabbage Chana Poriyal, Chips/Fryums/Papad, Curd, Kothimera Dosakai Pachadi, Kala Jamun', true),
  ('LH', '2026-10-23', 'snacks', 'Home Style, North Style, Home Style', true),
  ('LH', '2026-10-23', 'dinner', 'lemon Tea + sabja, Pani Puri', true),
  ('LH', '2026-10-10', 'breakfast', 'Chole bhature, Mix Veg Poha, Tomato chutney, Cholle Channa Curry, Bread + Butter + Jam, Sprouts (1 small cup)
Ragi Malt (Salt), Tea/Coffee/Milk, Egg Pepper Fry, Fresh Fruit Juice, Chocos, Boiled Chick Peas', true),
  ('LH', '2026-10-10', 'lunch', 'Cucumbar Yogurt Salad, Ghee Roti, White Rice, Moongdal tadka, Andhra Style Sambar, Mint Onion Pulao, Bendakai Masala Curry, Aloo 65, Chips/Fryums/Papad, Curd, Tomato Brinjal Pachadi, Kaja', true),
  ('LH', '2026-10-10', 'snacks', 'Home Style, Deep Fry, Home Style', true),
  ('LH', '2026-10-10', 'dinner', 'Hot Chocolate, Chocolate Eggless Cake', true),
  ('LH', '2026-10-31', 'breakfast', 'Chole bhature, Mix Veg Poha, Tomato chutney, Cholle Channa Curry, Bread + Butter + Jam, Sprouts (1 small cup)
Ragi Malt (Salt), Tea/Coffee/Milk, Egg Pepper Fry, Fresh Fruit Juice, Chocos, Boiled Chick Peas', true),
  ('LH', '2026-10-31', 'lunch', 'Cucumbar Yogurt Salad, Ghee Roti, White Rice, Moongdal tadka, Andhra Style Sambar, Mint Onion Pulao, Bendakai Masala Curry, Aloo 65, Chips/Fryums/Papad, Curd, Tomato Brinjal Pachadi, Kaja', true),
  ('LH', '2026-10-31', 'snacks', 'Home Style, Deep Fry, Home Style', true),
  ('LH', '2026-10-31', 'dinner', 'Hot Chocolate, Chocolate Eggless Cake', true),
  ('LH', '2026-10-11', 'breakfast', 'Veg Kitchidi, Gobi Paratha + Pickle + Curd, Peanut  Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Musli, Paneer Burji', true),
  ('LH', '2026-10-11', 'lunch', 'Onion Lemon Salad, Phulka, Pappulusu, Chicken gravy, Chicken Fry peice Biryani, Chatpata Paneer Biryani
Mirchi Ka salan
Raitha, Curd, Gongura Pachadi, Ice Cream', true),
  ('LH', '2026-10-11', 'dinner', 'Tea/Coffee/Milk, Vada Pav, Fresh Tomato Chilli Chutney', true),
  ('LH', '2026-10-25', 'breakfast', 'Veg Kitchidi, Gobi Paratha + Pickle + Curd, Peanut  Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Musli, Paneer Burji', true),
  ('LH', '2026-10-25', 'lunch', 'Onion Lemon Salad, Phulka, Pappulusu, Chicken gravy, Chicken Fry peice Biryani, Chatpata Paneer Biryani
Mirchi Ka salan
Raitha, Curd, Gongura Pachadi, Ice Cream', true),
  ('LH', '2026-10-25', 'dinner', 'Tea/Coffee/Milk, Vada Pav, Fresh Tomato Chilli Chutney', true),
  ('LH', '2026-10-12', 'breakfast', 'Semiya Bath, MasalA Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette, Fresh Fruit Juice, Corn Flakes, Peanut Sandals', true),
  ('LH', '2026-10-12', 'lunch', 'Cucumbar carrot Salad, Butter Roti, White Rice, Palak Dal, Kothimeera Rasam, Karvepaku karam Rice, Brinjal Tomato Curry, Chilli Jeera Aloo Poriyal, Chips/Fryums/Papad, Curd, Tomato & Dosakai vankai mukkala pachadi, Rasagulla', true),
  ('LH', '2026-10-12', 'snacks', 'Home Style, Boiled & Cook, Home Style', true),
  ('LH', '2026-10-12', 'dinner', 'Tea/Coffee/Milk, Soupy Mix veg Maggie (Carrot, Chilli, Beans, Coriander)', true),
  ('LH', '2026-10-26', 'breakfast', 'Semiya Bath, MasalA Dosa, Coconut Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Coriander & Chilli Omlette, Fresh Fruit Juice, Corn Flakes, Peanut Sandals', true),
  ('LH', '2026-10-26', 'lunch', 'Cucumbar carrot Salad, Butter Roti, White Rice, Palak Dal, Kothimeera Rasam, Karvepaku karam Rice, Brinjal Tomato Curry, Chilli Jeera Aloo Poriyal, Chips/Fryums/Papad, Curd, Tomato & Dosakai vankai mukkala pachadi, Rasagulla', true),
  ('LH', '2026-10-26', 'snacks', 'Home Style, Boiled & Cook, Home Style', true),
  ('LH', '2026-10-26', 'dinner', 'Tea/Coffee/Milk, Soupy Mix veg Maggie (Carrot, Chilli, Beans, Coriander)', true),
  ('LH', '2026-10-13', 'breakfast', 'Veg Pongal, vada, Dal Red chilli Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Chocos, Boiled Paneer Cubes', true),
  ('LH', '2026-10-13', 'lunch', 'Kosambari Moongdal (Roasted Peanuts, Pomogranate, corriender, grated coconut), Ghee Roti, White Rice, Dal Tadka, Vankaya Charu, Achaar Rice, Beerkai Ullipai Curry, Bendi Pakodi, Chips/Fryums/Papad, Curd, Vankai Pachadi, Ravva Kesari', true),
  ('LH', '2026-10-13', 'snacks', 'Indian, Deep Fry, Home Style', true),
  ('LH', '2026-10-13', 'dinner', 'Tea/Coffee/Milk, Dal Kachori, Pudina Chutney & Sweet Tamrind Chutney', true),
  ('LH', '2026-10-27', 'breakfast', 'Veg Pongal, vada, Dal Red chilli Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Boiled Egg, Fresh Fruit Juice, Chocos, Boiled Paneer Cubes', true),
  ('LH', '2026-10-27', 'lunch', 'Kosambari Moongdal (Roasted Peanuts, Pomogranate, corriender, grated coconut), Ghee Roti, White Rice, Dal Tadka, Vankaya Charu, Achaar Rice, Beerkai Ullipai Curry, Bendi Pakodi, Chips/Fryums/Papad, Curd, Vankai Pachadi, Ravva Kesari', true),
  ('LH', '2026-10-27', 'snacks', 'Indian, Deep Fry, Home Style', true),
  ('LH', '2026-10-27', 'dinner', 'Tea/Coffee/Milk, Dal Kachori, Pudina Chutney & Sweet Tamrind Chutney', true),
  ('LH', '2026-10-14', 'breakfast', 'Onion Pesarattu, Tomato Bath, Ginger Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Scrambled Egg, Fresh Fruit Juice, Corn Flakes, Boiled Chick Peas', true),
  ('LH', '2026-10-14', 'lunch', 'Vegetable Salad, Beetroot Roti, White Rice, Palak Dal, Mix veg Sambar, Vaangi bath, Kodi Iguru, Kadai Paneer Curry, Curd, Garlic Chutney, Sabudhana Payasam', true),
  ('LH', '2026-10-14', 'snacks', 'Andhra Home Style, North Style, Home Style', true),
  ('LH', '2026-10-14', 'dinner', 'Tea/Coffee/Milk, onion Corn Samosa (Big Size), Sauce/Chutney', true),
  ('LH', '2026-10-28', 'breakfast', 'Onion Pesarattu, Tomato Bath, Ginger Chutney, Sambar, Bread + Butter + Jam, Sprouts (1 small cup), Tea/Coffee/Milk, Masala Scrambled Egg, Fresh Fruit Juice, Corn Flakes, Boiled Chick Peas', true),
  ('LH', '2026-10-28', 'lunch', 'Vegetable Salad, Beetroot Roti, White Rice, Palak Dal, Mix veg Sambar, Vaangi bath, Kodi Iguru, Kadai Paneer Curry, Curd, Garlic Chutney, Sabudhana Payasam', true),
  ('LH', '2026-10-28', 'snacks', 'Andhra Home Style, North Style, Home Style', true),
  ('LH', '2026-10-28', 'dinner', 'Tea/Coffee/Milk, onion Corn Samosa (Big Size), Sauce/Chutney', true);